import { createTopic } from "./builder.js";

export const APTITUDE_UNITS = [
  {
    unitId: "apt-u1",
    subjectId: "aptitude",
    unitNumber: 1,
    title: "Unit 1 — Quantitative Aptitude",
    description: "Core arithmetic shortcuts: Number Systems, HCF/LCM, Percentages, Profit & Loss, Ratios, Averages, and Compound Interest.",
    learningObjectives: [
      "Apply divisibility rules and remainder theorems to number system problems",
      "Calculate HCF and LCM using prime factorization and division shortcuts",
      "Solve Percentage, Profit & Loss calculations using fractional equivalences",
      "Compute Simple Interest (SI) and Compound Interest (CI) using effective rate formulas",
    ],
    difficulty: "Beginner",
    estimatedHours: 3.5,
    prerequisites: ["High School Basic Math"],
    practiceQuestionsCount: 20,
    quizQuestionsCount: 15,
    order: 1,
  },
  {
    unitId: "apt-u2",
    subjectId: "aptitude",
    unitNumber: 2,
    title: "Unit 2 — Time, Speed & Work Systems",
    description: "Efficiency rates, reciprocal work days, negative work in Pipes & Cisterns, relative speed, and train platform crossing equations.",
    learningObjectives: [
      "Solve Time & Work problems using Total Work LCM efficiency method",
      "Model inlet filling vs outlet draining in Pipes & Cisterns",
      "Apply Relative Speed for same-direction vs opposite-direction train crossings",
      "Calculate upstream and downstream speeds in Boats & Streams",
    ],
    difficulty: "Intermediate",
    estimatedHours: 4.0,
    prerequisites: ["Unit 1 — Quantitative Aptitude"],
    practiceQuestionsCount: 20,
    quizQuestionsCount: 15,
    order: 2,
  },
  {
    unitId: "apt-u3",
    subjectId: "aptitude",
    unitNumber: 3,
    title: "Unit 3 — Logical Reasoning & Puzzles",
    description: "Series patterns, alphabet coding/decoding, family tree blood relations, direction compass vectors, Venn diagram syllogisms, and seating arrangements.",
    learningObjectives: [
      "Decode arithmetic, geometric, and alternating number and letter series",
      "Map multi-generational family trees and blood relations with gender symbols",
      "Solve displacement vectors and directional turns with Pythagorean theorem",
      "Evaluate Syllogism categorical propositions (All, Some, No, Some-Not) using Venn diagrams",
    ],
    difficulty: "Intermediate",
    estimatedHours: 4.0,
    prerequisites: ["Logical deduction ability"],
    practiceQuestionsCount: 22,
    quizQuestionsCount: 15,
    order: 3,
  },
  {
    unitId: "apt-u4",
    subjectId: "aptitude",
    unitNumber: 4,
    title: "Unit 4 — Verbal Ability & Reading Comprehension",
    description: "Subject-verb agreement grammar rules, vocabulary root words, synonyms/antonyms, sentence correction, and critical reading comprehension.",
    learningObjectives: [
      "Identify subject-verb agreement, modifier placement, and parallelism errors",
      "Expand corporate and placement vocabulary through Greek/Latin root words",
      "Detect tone, primary purpose, and implicit inferences in reading passages",
      "Reconstruct jumbled paragraphs (Para Jumbles) using transitional markers",
    ],
    difficulty: "Beginner",
    estimatedHours: 3.0,
    prerequisites: ["English language proficiency"],
    practiceQuestionsCount: 20,
    quizQuestionsCount: 15,
    order: 4,
  },
];

export const APTITUDE_CHAPTERS = APTITUDE_UNITS.map((u) => ({
  chapterId: `${u.unitId}-c1`,
  unitId: u.unitId,
  subjectId: "aptitude",
  chapterNumber: 1,
  title: u.title.replace(/Unit \d+ — /, ""),
  description: u.description,
  order: u.unitNumber,
}));

export const APTITUDE_TOPICS = [
  // Unit 1 Topics
  createTopic({
    topicId: "apt-u1-numbers-percentages",
    chapterId: "apt-u1-c1",
    unitId: "apt-u1",
    subjectId: "aptitude",
    topicNumber: 1,
    title: "Number Systems, HCF/LCM & Percentages",
    summary: "Unit digits, remainder theorems, HCF x LCM = Product of numbers rule, fraction-to-percentage tables, and percentage change shortcuts.",
    difficulty: "Beginner",
    timeComplexity: "O(log(min(A, B))) Euclidean HCF",
    spaceComplexity: "O(1)",
    subtopics: ["Divisibility Rules (2 to 13)", "Euclidean Algorithm for HCF", "Fraction-to-Percentage Memorization Table", "Successive Percentage Changes Formula"],
  }),
  createTopic({
    topicId: "apt-u1-profit-loss-interest",
    chapterId: "apt-u1-c1",
    unitId: "apt-u1",
    subjectId: "aptitude",
    topicNumber: 2,
    title: "Profit & Loss, Ratios, Averages & Compound Interest",
    summary: "Cost Price vs Selling Price, marked price and discounts, ratio mixtures and alligation, weighted averages, and CI compound growth formula.",
    difficulty: "Beginner",
    timeComplexity: "O(1)",
    spaceComplexity: "O(1)",
    subtopics: ["Markup & Discount Calculations", "Rule of Alligation for Mixtures", "Weighted Average Formula", "Difference between CI and SI for 2 & 3 Years"],
  }),

  // Unit 2 Topics
  createTopic({
    topicId: "apt-u2-time-and-work",
    chapterId: "apt-u2-c1",
    unitId: "apt-u2",
    subjectId: "aptitude",
    topicNumber: 1,
    title: "Time and Work & Pipes and Cisterns",
    summary: "LCM total-work framework, worker efficiencies, alternate day work schedules, negative work efficiency of leakage pipes.",
    difficulty: "Intermediate",
    timeComplexity: "O(1)",
    spaceComplexity: "O(1)",
    subtopics: ["Total Units of Work LCM Method", "Individual & Combined Daily Efficiency", "Pipes Filling vs Draining Leakage", "Work Done with Alternate Day Shifts"],
  }),
  createTopic({
    topicId: "apt-u2-speed-distance-trains",
    chapterId: "apt-u2-c1",
    unitId: "apt-u2",
    subjectId: "aptitude",
    topicNumber: 2,
    title: "Time Speed Distance, Trains & Boats/Streams",
    summary: "km/h to m/s unit conversion, relative speed when moving towards vs away, train crossing poles vs bridges, and upstream/downstream water vectors.",
    difficulty: "Intermediate",
    timeComplexity: "O(1)",
    spaceComplexity: "O(1)",
    subtopics: ["Speed = Distance / Time Conversion (5/18 factor)", "Relative Speed in Same vs Opposite Direction", "Train Crossing Moving vs Stationary Objects", "Boats Speed = (Downstream + Upstream) / 2"],
  }),

  // Unit 3 Topics
  createTopic({
    topicId: "apt-u3-series-coding-blood",
    chapterId: "apt-u3-c1",
    unitId: "apt-u3",
    subjectId: "aptitude",
    topicNumber: 1,
    title: "Number Series, Coding-Decoding & Blood Relations",
    summary: "Arithmetic/geometric difference sequences, alphabet position shifts (EJOTY rule), family generation tree diagrams, and coded relations.",
    difficulty: "Intermediate",
    timeComplexity: "O(N)",
    spaceComplexity: "O(1)",
    subtopics: ["Detecting Polynomial & Geometric Number Series", "Alphabet Letter Forward & Reverse Coding (EJOTY)", "Family Tree Standard Symbol Mapping", "Coded Blood Relations (A + B means A is father of B)"],
  }),
  createTopic({
    topicId: "apt-u3-syllogism-seating",
    chapterId: "apt-u3-c1",
    unitId: "apt-u3",
    subjectId: "aptitude",
    topicNumber: 2,
    title: "Direction Sense, Syllogisms & Seating Arrangements",
    summary: "Compass heading rotations, Pythagoras displacement, Venn diagram syllogisms (validity rules), and circular/linear seating puzzles.",
    difficulty: "Intermediate",
    timeComplexity: "O(1)",
    spaceComplexity: "O(1)",
    subtopics: ["Cardinal Directions & Angle Rotations", "Venn Diagram Syllogism Quantifiers (All, Some, No)", "Circular Seating Facing Inwards vs Outwards", "Linear Row Constraints & Elimination Technique"],
  }),

  // Unit 4 Topics
  createTopic({
    topicId: "apt-u4-grammar-vocabulary",
    chapterId: "apt-u4-c1",
    unitId: "apt-u4",
    subjectId: "aptitude",
    topicNumber: 1,
    title: "Grammar Rules, Sentence Correction & Vocabulary",
    summary: "Subject-verb agreement, dangling modifiers, tense consistency, high-frequency corporate GRE/placement word roots, and antonyms.",
    difficulty: "Beginner",
    timeComplexity: "O(1)",
    spaceComplexity: "O(1)",
    subtopics: ["Subject-Verb Inversion & Plural Traps", "Parallelism in Sentences", "Root Words, Prefixes & Suffixes", "Common Placement Confusable Words"],
  }),
  createTopic({
    topicId: "apt-u4-reading-comprehension",
    chapterId: "apt-u4-c1",
    unitId: "apt-u4",
    subjectId: "aptitude",
    topicNumber: 2,
    title: "Reading Comprehension & Critical Reasoning",
    summary: "Skimming vs scanning, identifying main idea vs supporting details, author tone detection, inference deduction, and assumption evaluation.",
    difficulty: "Intermediate",
    timeComplexity: "O(Passage Length)",
    spaceComplexity: "O(1)",
    subtopics: ["Central Theme vs Detail Questions", "Inferential & Implied Meaning Deduction", "Strengthening & Weakening Arguments", "Para-Jumble Sentence Sequencing Rules"],
  }),
];
