import { createTopic } from "./builder.js";

export const CN_UNITS = [
  {
    unitId: "cn-u1",
    subjectId: "cn",
    unitNumber: 1,
    title: "Unit 1 — Networking Fundamentals",
    description: "Computer networks classifications, LAN/MAN/WAN, topologies, network devices (Hubs, Switches, Routers), and OSI vs TCP/IP models.",
    learningObjectives: [
      "Understand network topologies (Star, Mesh, Bus, Ring)",
      "Analyze the 7 layers of the OSI model and data encapsulation",
      "Map OSI layers to the 4-layer TCP/IP Internet protocol suite",
      "Contrast Hubs (Layer 1), Switches (Layer 2), and Routers (Layer 3)",
    ],
    difficulty: "Beginner",
    estimatedHours: 3.0,
    prerequisites: ["Basic Computer Principles"],
    practiceQuestionsCount: 12,
    quizQuestionsCount: 10,
    order: 1,
  },
  {
    unitId: "cn-u2",
    subjectId: "cn",
    unitNumber: 2,
    title: "Unit 2 — Physical & Data Link Layer",
    description: "Guided/unguided media, circuit vs packet switching, framing, error detection (CRC, Checksum), flow control, MAC addresses, and Ethernet.",
    learningObjectives: [
      "Distinguish circuit switching from datagram packet switching",
      "Calculate Cyclic Redundancy Check (CRC) polynomial remainders",
      "Analyze sliding window protocols (Stop-and-Wait, Go-Back-N, Selective Repeat)",
      "Explain CSMA/CD collision detection and Ethernet frame structures",
    ],
    difficulty: "Intermediate",
    estimatedHours: 4.0,
    prerequisites: ["Unit 1 — Networking Fundamentals"],
    practiceQuestionsCount: 15,
    quizQuestionsCount: 12,
    order: 2,
  },
  {
    unitId: "cn-u3",
    subjectId: "cn",
    unitNumber: 3,
    title: "Unit 3 — Network Layer",
    description: "IPv4 and IPv6 addressing, CIDR subnetting, packet forwarding, ARP, ICMP, DHCP, and routing protocols (Distance Vector, Link State).",
    learningObjectives: [
      "Perform Variable Length Subnet Masking (VLSM) and CIDR address calculations",
      "Trace Address Resolution Protocol (ARP) cache resolutions",
      "Analyze Distance Vector (Bellman-Ford / RIP) count-to-infinity problem",
      "Explain Link State (Dijkstra / OSPF) shortest path tree convergence",
    ],
    difficulty: "Advanced",
    estimatedHours: 5.0,
    prerequisites: ["Unit 2 — Data Link Layer"],
    practiceQuestionsCount: 20,
    quizQuestionsCount: 15,
    order: 3,
  },
  {
    unitId: "cn-u4",
    subjectId: "cn",
    unitNumber: 4,
    title: "Unit 4 — Transport Layer",
    description: "Port multiplexing, TCP vs UDP comparison, TCP 3-Way Handshake, connection teardown, sliding window flow control, and AIMD congestion control.",
    learningObjectives: [
      "Contrast reliable connection-oriented TCP with lightweight connectionless UDP",
      "Trace TCP SYN, SYN-ACK, ACK 3-way handshake and FIN-ACK teardown sequence",
      "Explain sliding window flow control with receiver advertised window (rwnd)",
      "Analyze slow start, congestion avoidance, fast retransmit, and fast recovery (AIMD)",
    ],
    difficulty: "Advanced",
    estimatedHours: 5.0,
    prerequisites: ["Unit 3 — Network Layer"],
    practiceQuestionsCount: 22,
    quizQuestionsCount: 15,
    order: 4,
  },
  {
    unitId: "cn-u5",
    subjectId: "cn",
    unitNumber: 5,
    title: "Unit 5 — Application Layer",
    description: "Application protocols: DNS resolution hierarchy, HTTP/1.1 vs HTTP/2 vs HTTP/3, HTTPS TLS termination, FTP, SMTP, POP3, IMAP, and SSH.",
    learningObjectives: [
      "Trace recursive vs iterative DNS resolution through Root, TLD, and Authoritative servers",
      "Compare HTTP/1.1 pipelining, HTTP/2 multiplexing streams, and HTTP/3 QUIC UDP",
      "Explain email delivery workflows across SMTP submission and POP3/IMAP retrieval",
      "Understand secure cryptographic shell authentication in SSH",
    ],
    difficulty: "Intermediate",
    estimatedHours: 4.0,
    prerequisites: ["Unit 4 — Transport Layer"],
    practiceQuestionsCount: 18,
    quizQuestionsCount: 12,
    order: 5,
  },
  {
    unitId: "cn-u6",
    subjectId: "cn",
    unitNumber: 6,
    title: "Unit 6 — Network Security",
    description: "Symmetric vs asymmetric encryption, RSA, Digital Signatures, SSL/TLS handshake, Packet-filtering firewalls, VPNs, and common cyber attacks.",
    learningObjectives: [
      "Compare AES symmetric block ciphers with RSA asymmetric public-key cryptography",
      "Walk through the TLS 1.3 cryptographic handshake and certificate verification",
      "Configure stateful packet inspection firewalls and IPSec VPN tunnels",
      "Analyze Man-In-The-Middle (MITM), SYN flood DDoS, and DNS spoofing vectors",
    ],
    difficulty: "Advanced",
    estimatedHours: 4.5,
    prerequisites: ["Unit 5 — Application Layer"],
    practiceQuestionsCount: 18,
    quizQuestionsCount: 12,
    order: 6,
  },
];

export const CN_CHAPTERS = CN_UNITS.map((u) => ({
  chapterId: `${u.unitId}-c1`,
  unitId: u.unitId,
  subjectId: "cn",
  chapterNumber: 1,
  title: u.title.replace(/Unit \d+ — /, ""),
  description: u.description,
  order: u.unitNumber,
}));

export const CN_TOPICS = [
  // Unit 1 Topics
  createTopic({
    topicId: "cn-u1-osi-tcpip",
    chapterId: "cn-u1-c1",
    unitId: "cn-u1",
    subjectId: "cn",
    topicNumber: 1,
    title: "OSI Model vs TCP/IP Protocol Stack",
    summary: "7-layer OSI conceptual architecture vs 4-layer pragmatic TCP/IP Internet model, data encapsulation, headers, and trailers.",
    difficulty: "Beginner",
    timeComplexity: "O(1)",
    spaceComplexity: "O(1)",
    subtopics: ["Physical, Data Link, Network, Transport, Session, Presentation, Application", "Encapsulation & Decapsulation (PDU, Packet, Frame)", "Layer Responsibilities & Protocols"],
  }),
  createTopic({
    topicId: "cn-u1-topologies-devices",
    chapterId: "cn-u1-c1",
    unitId: "cn-u1",
    subjectId: "cn",
    topicNumber: 2,
    title: "Network Topologies & Network Hardware Devices",
    summary: "Star, Mesh, Bus topologies, collision vs broadcast domains, Hubs, Layer-2 Switches with CAM tables, and Layer-3 Routers.",
    difficulty: "Beginner",
    timeComplexity: "O(1)",
    spaceComplexity: "O(1)",
    subtopics: ["Star, Mesh, Bus & Ring Fault Tolerance", "Hub vs Switch Collision Domains", "Switch MAC Address Learning (CAM Table)", "Router IP Routing Table"],
  }),

  // Unit 2 Topics
  createTopic({
    topicId: "cn-u2-framing-error-control",
    chapterId: "cn-u2-c1",
    unitId: "cn-u2",
    subjectId: "cn",
    topicNumber: 1,
    title: "Framing, Error Detection (CRC) & Correction",
    summary: "Bit-stuffing and byte-stuffing framing, parity checks, Internet checksum, and Cyclic Redundancy Check (CRC) polynomial division.",
    difficulty: "Intermediate",
    timeComplexity: "O(N) Packet Size",
    spaceComplexity: "O(1)",
    subtopics: ["Character vs Bit Stuffing (Flag Bytes)", "Cyclic Redundancy Check (CRC) Polynomial Math", "Hamming Distance & Error Correction Codes"],
  }),
  createTopic({
    topicId: "cn-u2-flow-control-ethernet",
    chapterId: "cn-u2-c1",
    unitId: "cn-u2",
    subjectId: "cn",
    topicNumber: 2,
    title: "Sliding Window Protocols, MAC & Ethernet CSMA/CD",
    summary: "Stop-and-Wait, Go-Back-N, Selective Repeat window calculations, 48-bit MAC addressing, and Ethernet CSMA/CD backoff.",
    difficulty: "Intermediate",
    timeComplexity: "O(Window Size)",
    spaceComplexity: "O(Window Size)",
    subtopics: ["Stop-and-Wait Throughput & Efficiency", "Go-Back-N vs Selective Repeat Window Sizes", "CSMA/CD Carrier Sense & Binary Exponential Backoff", "Ethernet Frame Format (Preamble, SFD, Payload, FCS)"],
  }),

  // Unit 3 Topics
  createTopic({
    topicId: "cn-u3-ip-addressing-cidr",
    chapterId: "cn-u3-c1",
    unitId: "cn-u3",
    subjectId: "cn",
    topicNumber: 1,
    title: "IPv4, IPv6 Addressing & CIDR Subnetting",
    summary: "Classful vs Classless Inter-Domain Routing (CIDR), network/broadcast addresses, subnet masks, and IPv4 vs IPv6 128-bit headers.",
    difficulty: "Intermediate",
    timeComplexity: "O(1) Bitwise Mask",
    spaceComplexity: "O(1)",
    subtopics: ["CIDR Notation & Slash Masking (/24, /28)", "Subnetting & Host Calculation Formulas", "IPv6 Hexadecimal Compression Rules", "NAT (Network Address Translation) & Private IP Ranges"],
  }),
  createTopic({
    topicId: "cn-u3-routing-algorithms",
    chapterId: "cn-u3-c1",
    unitId: "cn-u3",
    subjectId: "cn",
    topicNumber: 2,
    title: "ARP, ICMP & Routing Algorithms (Distance Vector, Link State)",
    summary: "Address Resolution Protocol (ARP), ICMP ping/traceroute, Distance Vector routing (RIP) vs Link State routing (OSPF).",
    difficulty: "Advanced",
    timeComplexity: "Dijkstra: O(V log V + E)",
    spaceComplexity: "O(V)",
    subtopics: ["ARP Request/Reply & ARP Poisoning", "ICMP Echo & Time-Exceeded Messages", "Bellman-Ford Distance Vector & Count-to-Infinity", "Dijkstra Link State OSPF Shortest Path Tree"],
  }),

  // Unit 4 Topics
  createTopic({
    topicId: "cn-u4-tcp-udp-comparison",
    chapterId: "cn-u4-c1",
    unitId: "cn-u4",
    subjectId: "cn",
    topicNumber: 1,
    title: "TCP vs UDP & Port Multiplexing",
    summary: "16-bit port numbers, well-known vs ephemeral ports, reliability vs low-latency streaming trade-offs in TCP vs UDP.",
    difficulty: "Intermediate",
    timeComplexity: "O(1)",
    spaceComplexity: "O(Buffer Size)",
    subtopics: ["TCP 20-Byte Header vs UDP 8-Byte Header", "Port Addressing & Socket Tuple Identification", "When to Choose UDP (VoIP, DNS, Gaming, QUIC)"],
  }),
  createTopic({
    topicId: "cn-u4-tcp-handshake-congestion",
    chapterId: "cn-u4-c1",
    unitId: "cn-u4",
    subjectId: "cn",
    topicNumber: 2,
    title: "TCP 3-Way Handshake, Flow & Congestion Control",
    summary: "SYN/SYN-ACK/ACK sequence numbers, FIN teardown, receiver window flow control, and AIMD congestion window states.",
    difficulty: "Advanced",
    timeComplexity: "O(1)",
    spaceComplexity: "O(Window Buffer)",
    subtopics: ["3-Way Handshake Sequence & SYN Flood Attacks", "4-Way Teardown & TIME_WAIT State Importance", "Sliding Window Flow Control (rwnd)", "Slow Start, Congestion Avoidance, Fast Retransmit (cwnd)"],
  }),

  // Unit 5 Topics
  createTopic({
    topicId: "cn-u5-dns-http-https",
    chapterId: "cn-u5-c1",
    unitId: "cn-u5",
    subjectId: "cn",
    topicNumber: 1,
    title: "DNS Architecture & HTTP Evolution (HTTP/1.1, HTTP/2, HTTP/3)",
    summary: "Hierarchical DNS tree, A/CNAME/MX records, HTTP request/response headers, keep-alive, binary framing in HTTP/2, and QUIC in HTTP/3.",
    difficulty: "Intermediate",
    timeComplexity: "O(1) Cached Lookup",
    spaceComplexity: "O(N)",
    subtopics: ["Root, TLD & Authoritative DNS Resolution", "HTTP/1.1 Head-of-Line Blocking", "HTTP/2 Binary Framing & Multiplexed Streams", "HTTP/3 UDP-based QUIC Protocol"],
  }),
  createTopic({
    topicId: "cn-u5-email-protocols-ssh",
    chapterId: "cn-u5-c1",
    unitId: "cn-u5",
    subjectId: "cn",
    topicNumber: 2,
    title: "Email Protocols (SMTP, POP3, IMAP) & Secure Shell (SSH)",
    summary: "Mail transfer agents, port 25/587 SMTP push vs POP3/IMAP pull, asymmetric public-key authentication, and cryptographic SSH tunnels.",
    difficulty: "Intermediate",
    timeComplexity: "O(1)",
    spaceComplexity: "O(1)",
    subtopics: ["SMTP Message Transfer Architecture", "POP3 Local Download vs IMAP Server Sync", "SSH Asymmetric Key Exchange & Host Verification", "DHCP DORA IP Lease Allocation"],
  }),

  // Unit 6 Topics
  createTopic({
    topicId: "cn-u6-encryption-tls",
    chapterId: "cn-u6-c1",
    unitId: "cn-u6",
    subjectId: "cn",
    topicNumber: 1,
    title: "Cryptography, SSL/TLS Handshake & Certificates",
    summary: "Symmetric AES vs asymmetric RSA/ECC, digital signatures, certificate authorities (CA), and TLS 1.3 session key derivation.",
    difficulty: "Advanced",
    timeComplexity: "O(1)",
    spaceComplexity: "O(Key Length)",
    subtopics: ["Symmetric vs Asymmetric Cryptographic Primitives", "Digital Signatures & SHA-256 Hashing", "Certificate Authority (CA) Chain of Trust", "TLS 1.3 1-RTT Handshake Sequence"],
  }),
  createTopic({
    topicId: "cn-u6-firewalls-cyberattacks",
    chapterId: "cn-u6-c1",
    unitId: "cn-u6",
    subjectId: "cn",
    topicNumber: 2,
    title: "Firewalls, VPNs & Common Network Attacks",
    summary: "Packet-filtering and stateful firewalls, IPSec/WireGuard VPNs, DDoS attack mitigation, ARP spoofing, and MITM defenses.",
    difficulty: "Advanced",
    timeComplexity: "O(Rule Count) Firewall",
    spaceComplexity: "O(State Table)",
    subtopics: ["Stateful Packet Inspection (SPI) Firewalls", "IPSec & WireGuard Encrypted Tunneling", "DDoS Mitigation (SYN Cookies, Rate Limiting)", "DNS Spoofing & ARP Cache Poisoning Defenses"],
  }),
];
