import { createTopic } from "./builder.js";

export const DBMS_UNITS = [
  {
    unitId: "dbms-u1",
    subjectId: "dbms",
    unitNumber: 1,
    title: "Unit 1 — DBMS Fundamentals",
    description: "Database concepts, File System limitations, three-schema architecture, data independence, and database engine components.",
    learningObjectives: [
      "Distinguish file systems from modern relational database systems",
      "Understand physical, logical, and external schema layers",
      "Explain logical and physical data independence",
      "Identify core components of DBMS engines (Storage Engine, Query Processor)",
    ],
    difficulty: "Beginner",
    estimatedHours: 3.0,
    prerequisites: ["Basic Operating System Principles"],
    practiceQuestionsCount: 12,
    quizQuestionsCount: 10,
    order: 1,
  },
  {
    unitId: "dbms-u2",
    subjectId: "dbms",
    unitNumber: 2,
    title: "Unit 2 — ER Model",
    description: "Entity-Relationship modeling, attributes, relationships, cardinalities, weak entities, generalization, and schema design.",
    learningObjectives: [
      "Construct comprehensive Entity-Relationship diagrams",
      "Map 1:1, 1:N, and M:N relationships to relational tables",
      "Model weak entities and identifying relationships",
      "Apply generalization, specialization, and aggregation hierarchies",
    ],
    difficulty: "Beginner",
    estimatedHours: 3.5,
    prerequisites: ["Unit 1 — DBMS Fundamentals"],
    practiceQuestionsCount: 15,
    quizQuestionsCount: 10,
    order: 2,
  },
  {
    unitId: "dbms-u3",
    subjectId: "dbms",
    unitNumber: 3,
    title: "Unit 3 — Relational Model",
    description: "Relations, tuples, candidate keys, foreign keys, integrity constraints, and Relational Algebra query operators.",
    learningObjectives: [
      "Define relational tuples, domains, and relation schemas",
      "Identify Super Keys, Candidate Keys, Primary Keys, and Foreign Keys",
      "Enforce entity integrity and referential integrity constraints",
      "Execute Relational Algebra operations (Select, Project, Cartesian Product, Join, Division)",
    ],
    difficulty: "Intermediate",
    estimatedHours: 4.0,
    prerequisites: ["Unit 2 — ER Model"],
    practiceQuestionsCount: 18,
    quizQuestionsCount: 12,
    order: 3,
  },
  {
    unitId: "dbms-u4",
    subjectId: "dbms",
    unitNumber: 4,
    title: "Unit 4 — SQL (Structured Query Language)",
    description: "DDL, DML, DQL statements, complex multi-table joins, subqueries, grouping aggregations, views, and index creation.",
    learningObjectives: [
      "Write efficient DDL (CREATE, ALTER, DROP) and DML (INSERT, UPDATE, DELETE)",
      "Master multi-table INNER, LEFT, RIGHT, FULL OUTER, and CROSS joins",
      "Construct correlated subqueries, window functions, and CTEs",
      "Implement GROUP BY, HAVING, and aggregate grouping rollups",
    ],
    difficulty: "Intermediate",
    estimatedHours: 5.5,
    prerequisites: ["Unit 3 — Relational Model"],
    practiceQuestionsCount: 25,
    quizQuestionsCount: 15,
    order: 4,
  },
  {
    unitId: "dbms-u5",
    subjectId: "dbms",
    unitNumber: 5,
    title: "Unit 5 — Normalization & Transactions",
    description: "Functional dependencies, 1NF, 2NF, 3NF, BCNF, ACID transaction guarantees, concurrency control, serializability, and 2PL.",
    learningObjectives: [
      "Calculate functional dependency closures and candidate keys",
      "Decompose schemas into 1NF, 2NF, 3NF, and Boyce-Codd Normal Form (BCNF)",
      "Analyze ACID guarantees (Atomicity, Consistency, Isolation, Durability)",
      "Enforce concurrency via Two-Phase Locking (2PL), deadlock graphs, and WAL recovery",
    ],
    difficulty: "Advanced",
    estimatedHours: 5.0,
    prerequisites: ["Unit 4 — SQL"],
    practiceQuestionsCount: 20,
    quizQuestionsCount: 15,
    order: 5,
  },
  {
    unitId: "dbms-u6",
    subjectId: "dbms",
    unitNumber: 6,
    title: "Unit 6 — Advanced Database Concepts",
    description: "B/B+ tree disk indexing, query execution plans, cost-based query optimization, distributed NoSQL databases, and MongoDB.",
    learningObjectives: [
      "Analyze dense vs sparse indexes and multi-level B+ Tree disk structures",
      "Interpret EXPLAIN query execution plans and index scans vs table scans",
      "Understand query parsing, logical optimization, and physical plan generation",
      "Compare relational databases with document NoSQL (MongoDB) schemas",
    ],
    difficulty: "Advanced",
    estimatedHours: 4.5,
    prerequisites: ["Unit 5 — Transactions"],
    practiceQuestionsCount: 18,
    quizQuestionsCount: 12,
    order: 6,
  },
];

export const DBMS_CHAPTERS = DBMS_UNITS.map((u) => ({
  chapterId: `${u.unitId}-c1`,
  unitId: u.unitId,
  subjectId: "dbms",
  chapterNumber: 1,
  title: u.title.replace(/Unit \d+ — /, ""),
  description: u.description,
  order: u.unitNumber,
}));

export const DBMS_TOPICS = [
  // Unit 1 Topics
  createTopic({
    topicId: "dbms-u1-intro",
    chapterId: "dbms-u1-c1",
    unitId: "dbms-u1",
    subjectId: "dbms",
    topicNumber: 1,
    title: "Database & DBMS Fundamentals",
    summary: "Role of DBMS in persistence, concurrent access, integrity enforcement, and drawbacks of raw file system storage.",
    difficulty: "Beginner",
    timeComplexity: "O(1) to O(N)",
    spaceComplexity: "O(N)",
    subtopics: ["Data vs Information", "File Processing Disadvantages", "DBMS Advantages", "ACID Compliance Overview"],
  }),
  createTopic({
    topicId: "dbms-u1-architecture",
    chapterId: "dbms-u1-c1",
    unitId: "dbms-u1",
    subjectId: "dbms",
    topicNumber: 2,
    title: "DBMS 3-Schema Architecture & Data Independence",
    summary: "ANSI/SPARC 3-tier architecture: External (views), Conceptual (logical tables), and Internal (physical disk storage).",
    difficulty: "Beginner",
    timeComplexity: "O(1)",
    spaceComplexity: "O(1)",
    subtopics: ["Physical vs Logical Schemas", "Physical Data Independence", "Logical Data Independence", "Database Administrator (DBA) Role"],
  }),

  // Unit 2 Topics
  createTopic({
    topicId: "dbms-u2-er-model",
    chapterId: "dbms-u2-c1",
    unitId: "dbms-u2",
    subjectId: "dbms",
    topicNumber: 1,
    title: "Entity, Attribute, Relationship & ER Diagrams",
    summary: "Entities, simple/composite/multivalued attributes, relationships, mapping cardinalities (1:1, 1:N, M:N), and ER notations.",
    difficulty: "Beginner",
    timeComplexity: "O(1)",
    spaceComplexity: "O(N)",
    subtopics: ["Entity Sets & Keys", "Attribute Classifications", "Relationship Types & Cardinalities", "ER Diagram Construction"],
  }),
  createTopic({
    topicId: "dbms-u2-advanced-er",
    chapterId: "dbms-u2-c1",
    unitId: "dbms-u2",
    subjectId: "dbms",
    topicNumber: 2,
    title: "Weak Entities, Generalization & Specialization",
    summary: "Weak entities with discriminating partial keys, ISA hierarchies, generalization, specialization, and aggregation.",
    difficulty: "Intermediate",
    timeComplexity: "O(1)",
    spaceComplexity: "O(N)",
    subtopics: ["Weak Entity Identification", "Total vs Partial Participation", "Generalization (Top-Down)", "Specialization (Bottom-Up)"],
  }),

  // Unit 3 Topics
  createTopic({
    topicId: "dbms-u3-relational-keys",
    chapterId: "dbms-u3-c1",
    unitId: "dbms-u3",
    subjectId: "dbms",
    topicNumber: 1,
    title: "Relational Keys & Integrity Constraints",
    summary: "Formal definitions of Super Key, Candidate Key, Primary Key, Foreign Key, and domain/referential integrity constraints.",
    difficulty: "Intermediate",
    timeComplexity: "O(1)",
    spaceComplexity: "O(N)",
    subtopics: ["Candidate Key Minimality", "Primary Key Uniqueness & Not-Null", "Foreign Key Referential Actions (Cascade, Set Null)"],
  }),
  createTopic({
    topicId: "dbms-u3-relational-algebra",
    chapterId: "dbms-u3-c1",
    unitId: "dbms-u3",
    subjectId: "dbms",
    topicNumber: 2,
    title: "Relational Algebra Operations",
    summary: "Procedural query language: Selection (σ), Projection (π), Cross Product (×), Set Union/Difference, Natural Join (⋈), and Division (÷).",
    difficulty: "Intermediate",
    timeComplexity: "O(N) to O(N*M)",
    spaceComplexity: "O(N)",
    subtopics: ["Selection & Projection Filters", "Theta Join and Equi-Join", "Division Operator for Universal Queries", "Relational Completeness"],
  }),

  // Unit 4 Topics
  createTopic({
    topicId: "dbms-u4-ddl-dml",
    chapterId: "dbms-u4-c1",
    unitId: "dbms-u4",
    subjectId: "dbms",
    topicNumber: 1,
    title: "SQL DDL, DML & Basic Querying",
    summary: "CREATE, ALTER, DROP, TRUNCATE, INSERT, UPDATE, DELETE, and SELECT queries with WHERE, ORDER BY, and LIMIT.",
    difficulty: "Beginner",
    timeComplexity: "O(1) to O(N)",
    spaceComplexity: "O(N)",
    subtopics: ["DDL Syntax and Table Creation", "DML Data Mutation Statements", "WHERE Filtering Predicates", "NULL Value Semantics in SQL"],
  }),
  createTopic({
    topicId: "dbms-u4-joins-aggregations",
    chapterId: "dbms-u4-c1",
    unitId: "dbms-u4",
    subjectId: "dbms",
    topicNumber: 2,
    title: "SQL Joins, Grouping & Aggregations",
    summary: "INNER, LEFT, RIGHT, FULL OUTER joins, GROUP BY grouping, HAVING condition filters, and COUNT, SUM, AVG aggregate functions.",
    difficulty: "Intermediate",
    timeComplexity: "O(N log N) to O(N*M)",
    spaceComplexity: "O(N)",
    subtopics: ["Join Mechanics & Execution", "GROUP BY Aggregation Buckets", "HAVING vs WHERE Distinctions", "Window Functions (ROW_NUMBER, RANK)"],
  }),
  createTopic({
    topicId: "dbms-u4-subqueries-views",
    chapterId: "dbms-u4-c1",
    unitId: "dbms-u4",
    subjectId: "dbms",
    topicNumber: 3,
    title: "Subqueries, Views & Indexes in SQL",
    summary: "Correlated subqueries, Common Table Expressions (WITH clauses), virtual views, and B-Tree index creation statements.",
    difficulty: "Intermediate",
    timeComplexity: "O(log N) Indexed Search",
    spaceComplexity: "O(N)",
    subtopics: ["Correlated Subqueries vs Nested Subqueries", "Common Table Expressions (CTEs)", "Database Views & Materialized Views", "CREATE INDEX Statements"],
  }),

  // Unit 5 Topics
  createTopic({
    topicId: "dbms-u5-functional-dependencies",
    chapterId: "dbms-u5-c1",
    unitId: "dbms-u5",
    subjectId: "dbms",
    topicNumber: 1,
    title: "Functional Dependencies & Attribute Closure",
    summary: "Armstrong's axioms, calculating attribute closures X+, minimal cover, and determining Candidate Keys algorithmically.",
    difficulty: "Intermediate",
    timeComplexity: "O(N^2)",
    spaceComplexity: "O(N)",
    subtopics: ["Armstrong's Inference Rules", "Attribute Closure Calculation", "Candidate Key Derivation", "Canonical Minimal Cover"],
  }),
  createTopic({
    topicId: "dbms-u5-normalization",
    chapterId: "dbms-u5-c1",
    unitId: "dbms-u5",
    subjectId: "dbms",
    topicNumber: 2,
    title: "Database Normalization: 1NF, 2NF, 3NF & BCNF",
    summary: "Eliminating redundancy and update/delete anomalies via decomposition into 1NF, 2NF (no partial FD), 3NF (no transitive FD), and BCNF.",
    difficulty: "Advanced",
    timeComplexity: "O(N^2)",
    spaceComplexity: "O(N)",
    subtopics: ["Anomalies (Insertion, Deletion, Update)", "First Normal Form (Atomicity)", "Second Normal Form (Full Dependency)", "3NF & Boyce-Codd Normal Form"],
  }),
  createTopic({
    topicId: "dbms-u5-transactions-acid",
    chapterId: "dbms-u5-c1",
    unitId: "dbms-u5",
    subjectId: "dbms",
    topicNumber: 3,
    title: "Transactions, ACID Properties & Concurrency Control",
    summary: "Atomicity, Consistency, Isolation, Durability, serializability schedules, Two-Phase Locking (2PL), deadlock prevention, and WAL recovery.",
    difficulty: "Advanced",
    timeComplexity: "O(1) to O(N)",
    spaceComplexity: "O(N)",
    subtopics: ["ACID Guarantees Explained", "Conflict & View Serializability", "Two-Phase Locking (Rigorous & Strict 2PL)", "Deadlock Detection via Wait-For Graphs"],
  }),

  // Unit 6 Topics
  createTopic({
    topicId: "dbms-u6-indexing-btree",
    chapterId: "dbms-u6-c1",
    unitId: "dbms-u6",
    subjectId: "dbms",
    topicNumber: 1,
    title: "B-Tree & B+ Tree Indexing Internals",
    summary: "Dense vs sparse indexing, clustered vs secondary indexes, and disk-block I/O optimization using multi-way balanced B+ Trees.",
    difficulty: "Advanced",
    timeComplexity: "O(log_B N) Disk I/O",
    spaceComplexity: "O(N)",
    subtopics: ["Clustered vs Non-Clustered Indexes", "B+ Tree Node Structure & Pointers", "Sequential Leaf Traversal in B+ Trees", "Composite Index Column Order"],
  }),
  createTopic({
    topicId: "dbms-u6-query-optimization",
    chapterId: "dbms-u6-c1",
    unitId: "dbms-u6",
    subjectId: "dbms",
    topicNumber: 2,
    title: "Query Processing, Optimization & Execution Plans",
    summary: "Parsing, relational algebra tree transformation, cost-based optimizer heuristics, and EXPLAIN plan evaluation.",
    difficulty: "Advanced",
    timeComplexity: "O(N log N)",
    spaceComplexity: "O(N)",
    subtopics: ["Query Processing Pipeline Steps", "Heuristic Optimization (Pushing Selections)", "Cost-Based Plan Evaluation", "Interpreting EXPLAIN Output"],
  }),
  createTopic({
    topicId: "dbms-u6-nosql-mongodb",
    chapterId: "dbms-u6-c1",
    unitId: "dbms-u6",
    subjectId: "dbms",
    topicNumber: 3,
    title: "Distributed Databases, NoSQL & MongoDB Basics",
    summary: "CAP theorem, document/key-value/columnar stores, schema-less flexibility, and MongoDB aggregation pipelines vs SQL joins.",
    difficulty: "Intermediate",
    timeComplexity: "O(1) Key-Value to O(log N) Indexed",
    spaceComplexity: "O(N)",
    subtopics: ["SQL vs NoSQL Paradigms", "CAP Theorem Trade-Offs", "MongoDB Document & BSON Architecture", "Embedding vs Referencing in NoSQL"],
  }),
];
