import { createTopic } from "./builder.js";

export const DSA_UNITS = [
  {
    unitId: "dsa-u1",
    subjectId: "dsa",
    unitNumber: 1,
    title: "Unit 1 — Introduction & Algorithm Analysis",
    description: "Fundamental data structures, abstract data types, asymptotic analysis, Big-O, Omega, Theta, and complexity bounds.",
    learningObjectives: [
      "Understand abstract data types and structural classification",
      "Master Big-O, Big-Omega, and Big-Theta formal definitions",
      "Analyze best, average, and worst-case performance bounds",
      "Calculate space and auxiliary memory complexity of algorithms",
    ],
    difficulty: "Beginner",
    estimatedHours: 3.5,
    prerequisites: ["Basic Programming Logic", "High School Algebra"],
    practiceQuestionsCount: 12,
    quizQuestionsCount: 10,
    order: 1,
  },
  {
    unitId: "dsa-u2",
    subjectId: "dsa",
    unitNumber: 2,
    title: "Unit 2 — Arrays, Searching & Sorting",
    description: "1D/2D arrays, linear & binary search, and comprehensive comparison of comparison vs non-comparison sorting algorithms.",
    learningObjectives: [
      "Manipulate 1D and multi-dimensional memory layouts",
      "Implement logarithmic binary search and monotonic predicate boundaries",
      "Master QuickSort, MergeSort, HeapSort, and linear-time counting/radix sorts",
      "Evaluate stability, in-place behavior, and space-time complexity trade-offs",
    ],
    difficulty: "Intermediate",
    estimatedHours: 5.0,
    prerequisites: ["Unit 1 — Algorithm Analysis"],
    practiceQuestionsCount: 20,
    quizQuestionsCount: 15,
    order: 2,
  },
  {
    unitId: "dsa-u3",
    subjectId: "dsa",
    unitNumber: 3,
    title: "Unit 3 — Linked Lists",
    description: "Singly, doubly, and circular linked lists with pointer manipulation, reversal, cycle detection, and memory trade-offs.",
    learningObjectives: [
      "Construct node-based dynamic memory structures",
      "Execute safe insertion, deletion, and bidirectional traversal",
      "Implement Floyd's cycle detection and pointer reversal algorithms",
      "Analyze memory fragmentation and cache locality vs contiguous arrays",
    ],
    difficulty: "Intermediate",
    estimatedHours: 3.5,
    prerequisites: ["Pointers / Object References", "Memory Allocation"],
    practiceQuestionsCount: 15,
    quizQuestionsCount: 10,
    order: 3,
  },
  {
    unitId: "dsa-u4",
    subjectId: "dsa",
    unitNumber: 4,
    title: "Unit 4 — Stack & Queue",
    description: "LIFO and FIFO data structures, array/linked-list implementations, monotonic stacks, expression parsing, and priority queues.",
    learningObjectives: [
      "Implement Stack and Queue interfaces using arrays and dynamic lists",
      "Convert and evaluate Infix, Prefix, and Postfix mathematical expressions",
      "Apply monotonic stacks to next-greater-element interview problems",
      "Implement circular queues, deques, and binary heap priority queues",
    ],
    difficulty: "Intermediate",
    estimatedHours: 4.0,
    prerequisites: ["Unit 2 — Arrays", "Unit 3 — Linked Lists"],
    practiceQuestionsCount: 18,
    quizQuestionsCount: 12,
    order: 4,
  },
  {
    unitId: "dsa-u5",
    subjectId: "dsa",
    unitNumber: 5,
    title: "Unit 5 — Trees",
    description: "Hierarchical structures, binary search trees, self-balancing AVL rotations, binary heaps, and balanced B/B+ trees.",
    learningObjectives: [
      "Execute recursive and iterative tree traversals (Preorder, Inorder, Postorder, Level-Order)",
      "Build balanced Binary Search Trees and maintain ordering invariants",
      "Master self-balancing AVL tree single/double rotations",
      "Understand min/max heap arrays, heapify routines, and multiway B-Trees",
    ],
    difficulty: "Advanced",
    estimatedHours: 6.0,
    prerequisites: ["Recursion", "Dynamic Memory"],
    practiceQuestionsCount: 22,
    quizQuestionsCount: 15,
    order: 5,
  },
  {
    unitId: "dsa-u6",
    subjectId: "dsa",
    unitNumber: 6,
    title: "Unit 6 — Graphs",
    description: "Graph representations, BFS/DFS traversals, topological sorting, minimum spanning trees, and shortest path algorithms.",
    learningObjectives: [
      "Model real-world networks using Adjacency Matrices and Adjacency Lists",
      "Implement Breadth-First Search (BFS) and Depth-First Search (DFS)",
      "Detect cycles in directed and undirected graphs via Kahn's algorithm / DFS coloring",
      "Compute Minimum Spanning Trees (Prim's & Kruskal's) and Shortest Paths (Dijkstra, Bellman-Ford, Floyd-Warshall)",
    ],
    difficulty: "Advanced",
    estimatedHours: 6.5,
    prerequisites: ["Unit 4 — Queues", "Unit 5 — Trees"],
    practiceQuestionsCount: 25,
    quizQuestionsCount: 15,
    order: 6,
  },
  {
    unitId: "dsa-u7",
    subjectId: "dsa",
    unitNumber: 7,
    title: "Unit 7 — Advanced Algorithms",
    description: "Greedy choice property, divide & conquer paradigms, dynamic programming (memoization vs tabulation), and backtracking.",
    learningObjectives: [
      "Identify optimal substructure and overlapping subproblems in dynamic programming",
      "Formulate 1D and 2D state transitions (0/1 Knapsack, Longest Common Subsequence, Edit Distance)",
      "Implement backtracking search trees with bounding functions (N-Queens, Sudoku)",
      "Compare greedy heuristics vs guaranteed global optimal dynamic programming",
    ],
    difficulty: "Advanced",
    estimatedHours: 7.0,
    prerequisites: ["Recursion", "Mathematical Induction"],
    practiceQuestionsCount: 28,
    quizQuestionsCount: 15,
    order: 7,
  },
];

export const DSA_CHAPTERS = DSA_UNITS.map((u) => ({
  chapterId: `${u.unitId}-c1`,
  unitId: u.unitId,
  subjectId: "dsa",
  chapterNumber: 1,
  title: u.title.replace(/Unit \d+ — /, ""),
  description: u.description,
  order: u.unitNumber,
}));

export const DSA_TOPICS = [
  // Unit 1 Topics
  createTopic({
    topicId: "dsa-u1-intro-ds",
    chapterId: "dsa-u1-c1",
    unitId: "dsa-u1",
    subjectId: "dsa",
    topicNumber: 1,
    title: "Introduction to Data Structures",
    summary: "Foundational concepts of structuring, organizing, and accessing computational data efficiently in memory.",
    difficulty: "Beginner",
    timeComplexity: "O(1)",
    spaceComplexity: "O(N)",
    subtopics: ["Definition of Data Structure", "Need for Data Structures", "Memory Organization", "Static vs Dynamic Allocation"],
  }),
  createTopic({
    topicId: "dsa-u1-types-ds",
    chapterId: "dsa-u1-c1",
    unitId: "dsa-u1",
    subjectId: "dsa",
    topicNumber: 2,
    title: "Types of Data Structures",
    summary: "Taxonomy of data structures: linear vs non-linear, primitive vs non-primitive, static vs dynamic structures.",
    difficulty: "Beginner",
    timeComplexity: "O(1)",
    spaceComplexity: "O(N)",
    subtopics: ["Linear Structures (Arrays, Lists, Stacks)", "Non-Linear Structures (Trees, Graphs)", "Primitive vs User-defined"],
  }),
  createTopic({
    topicId: "dsa-u1-adt",
    chapterId: "dsa-u1-c1",
    unitId: "dsa-u1",
    subjectId: "dsa",
    topicNumber: 3,
    title: "Abstract Data Types (ADT)",
    summary: "Mathematical model for data types where behavior is defined by semantics without specifying concrete implementation details.",
    difficulty: "Beginner",
    timeComplexity: "O(1)",
    spaceComplexity: "O(1)",
    subtopics: ["Concept of Abstraction", "Encapsulation of State", "Common ADTs (List, Stack, Queue, Map)"],
  }),
  createTopic({
    topicId: "dsa-u1-algorithms",
    chapterId: "dsa-u1-c1",
    unitId: "dsa-u1",
    subjectId: "dsa",
    topicNumber: 4,
    title: "Algorithms & Characteristics",
    summary: "Formal definition of an algorithm, input-output determinism, finiteness, correctness, and language independence.",
    difficulty: "Beginner",
    timeComplexity: "O(1)",
    spaceComplexity: "O(1)",
    subtopics: ["Finiteness", "Definiteness", "Input/Output Properties", "Effectiveness"],
  }),
  createTopic({
    topicId: "dsa-u1-time-complexity",
    chapterId: "dsa-u1-c1",
    unitId: "dsa-u1",
    subjectId: "dsa",
    topicNumber: 5,
    title: "Time Complexity Analysis",
    summary: "Quantifying program execution steps as a function of input size N independently of physical CPU clock speed.",
    difficulty: "Beginner",
    timeComplexity: "O(1)",
    spaceComplexity: "O(1)",
    subtopics: ["Primitive Operations Counting", "Frequency Count Method", "Growth Rates Comparison", "Dominant Terms"],
  }),
  createTopic({
    topicId: "dsa-u1-space-complexity",
    chapterId: "dsa-u1-c1",
    unitId: "dsa-u1",
    subjectId: "dsa",
    topicNumber: 6,
    title: "Space Complexity & Auxiliary Memory",
    summary: "Measuring overall memory footprint: fixed instruction space, variable data allocation, and recursive call-stack depth.",
    difficulty: "Beginner",
    timeComplexity: "O(1)",
    spaceComplexity: "O(N)",
    subtopics: ["Total Space vs Auxiliary Space", "Recursion Call Stack Overhead", "In-Place Algorithm Criteria"],
  }),
  createTopic({
    topicId: "dsa-u1-asymptotic-notations",
    chapterId: "dsa-u1-c1",
    unitId: "dsa-u1",
    subjectId: "dsa",
    topicNumber: 7,
    title: "Asymptotic Analysis: Big O, Big Omega & Big Theta",
    summary: "Formal mathematical bounds: Big O (upper bound), Big Omega (lower bound), and Big Theta (tight bound).",
    difficulty: "Intermediate",
    timeComplexity: "O(1)",
    spaceComplexity: "O(1)",
    subtopics: ["Big O Formal Limit Definition", "Omega Lower Bound Analysis", "Theta Exact Bound", "Order of Growth Rankings"],
  }),
  createTopic({
    topicId: "dsa-u1-cases-analysis",
    chapterId: "dsa-u1-c1",
    unitId: "dsa-u1",
    subjectId: "dsa",
    topicNumber: 8,
    title: "Best, Average & Worst Case Analysis",
    summary: "Evaluating algorithmic behaviors across optimal input configurations, typical probability distributions, and adversarial inputs.",
    difficulty: "Intermediate",
    timeComplexity: "O(1)",
    spaceComplexity: "O(1)",
    subtopics: ["Worst Case Guarantees", "Average Case Expected Value", "Best Case Lower Limit", "Amortized Analysis Concept"],
  }),

  // Unit 2 Topics
  createTopic({
    topicId: "dsa-u2-arrays-intro",
    chapterId: "dsa-u2-c1",
    unitId: "dsa-u2",
    subjectId: "dsa",
    topicNumber: 1,
    title: "Arrays & Array Operations (1D and 2D)",
    summary: "Contiguous memory allocations, row-major and column-major address calculations, and O(1) random index access.",
    difficulty: "Beginner",
    timeComplexity: "O(1) Access, O(N) Insertion/Deletion",
    spaceComplexity: "O(N)",
    subtopics: ["Contiguous Memory Architecture", "Row-Major Address Formula", "Dynamic Arrays (Vectors/ArrayList)", "Boundary Checking"],
  }),
  createTopic({
    topicId: "dsa-u2-linear-binary-search",
    chapterId: "dsa-u2-c1",
    unitId: "dsa-u2",
    subjectId: "dsa",
    topicNumber: 2,
    title: "Linear Search vs Binary Search",
    summary: "Sequential scanning vs divide-and-conquer logarithmic search on sorted arrays with lower and upper bound variants.",
    difficulty: "Beginner",
    timeComplexity: "Linear: O(N), Binary: O(log N)",
    spaceComplexity: "O(1)",
    subtopics: ["Linear Scan Mechanics", "Binary Search Invariants", "Lower Bound & Upper Bound", "Search Space Reductions"],
  }),
  createTopic({
    topicId: "dsa-u2-elementary-sorts",
    chapterId: "dsa-u2-c1",
    unitId: "dsa-u2",
    subjectId: "dsa",
    topicNumber: 3,
    title: "Bubble, Selection & Insertion Sort",
    summary: "Quadratic comparison-based sorting algorithms: pairwise swapping, minimum element selection, and adaptive insertion.",
    difficulty: "Beginner",
    timeComplexity: "O(N^2)",
    spaceComplexity: "O(1)",
    subtopics: ["Bubble Sort Inversion Swapping", "Selection Sort Unstable Min-Pick", "Insertion Sort Adaptive Online Sorting"],
  }),
  createTopic({
    topicId: "dsa-u2-merge-sort",
    chapterId: "dsa-u2-c1",
    unitId: "dsa-u2",
    subjectId: "dsa",
    topicNumber: 4,
    title: "Merge Sort & Divide-and-Conquer",
    summary: "Divide, conquer, and combine paradigm: stable sorting with guaranteed O(N log N) runtime and auxiliary array merging.",
    difficulty: "Intermediate",
    timeComplexity: "O(N log N)",
    spaceComplexity: "O(N)",
    subtopics: ["Divide Step Splitting", "Two-Pointer Merge Routine", "Recurrence Relation T(N)=2T(N/2)+N", "Inversion Counting"],
  }),
  createTopic({
    topicId: "dsa-u2-quick-sort",
    chapterId: "dsa-u2-c1",
    unitId: "dsa-u2",
    subjectId: "dsa",
    topicNumber: 5,
    title: "Quick Sort & Partitioning Algorithms",
    summary: "In-place recursive divide-and-conquer using Lomuto and Hoare partitioning schemes with randomized pivot selection.",
    difficulty: "Intermediate",
    timeComplexity: "O(N log N) Average, O(N^2) Worst",
    spaceComplexity: "O(log N) Stack",
    subtopics: ["Lomuto Partition Scheme", "Hoare Dual-Pointer Partition", "Median-of-Three Pivot Selection", "Tail Call Optimization"],
  }),
  createTopic({
    topicId: "dsa-u2-heap-linear-sorts",
    chapterId: "dsa-u2-c1",
    unitId: "dsa-u2",
    subjectId: "dsa",
    topicNumber: 6,
    title: "Heap Sort, Counting Sort & Radix Sort",
    summary: "In-place heap-based sorting alongside non-comparison linear time integer sorting algorithms.",
    difficulty: "Advanced",
    timeComplexity: "Heap: O(N log N), Counting/Radix: O(N + K)",
    spaceComplexity: "Heap: O(1), Counting: O(K)",
    subtopics: ["Heapify Sorting Invariants", "Counting Sort Frequency Array", "Radix Sort Digit Extraction", "Comparison Lower Bound Omega(N log N)"],
  }),

  // Unit 3 Topics
  createTopic({
    topicId: "dsa-u3-singly-linked-list",
    chapterId: "dsa-u3-c1",
    unitId: "dsa-u3",
    subjectId: "dsa",
    topicNumber: 1,
    title: "Singly Linked List Operations",
    summary: "Node pointers, dynamic node allocation, head/tail pointer maintenance, and insertion/deletion at arbitrary positions.",
    difficulty: "Beginner",
    timeComplexity: "O(1) Head Insert, O(N) Arbitrary Search/Insert",
    spaceComplexity: "O(N)",
    subtopics: ["Node Anatomy & Pointers", "Insertion at Head / Tail / Position", "Deletion Logic and Memory Cleanup"],
  }),
  createTopic({
    topicId: "dsa-u3-doubly-circular-list",
    chapterId: "dsa-u3-c1",
    unitId: "dsa-u3",
    subjectId: "dsa",
    topicNumber: 2,
    title: "Doubly & Circular Linked Lists",
    summary: "Bidirectional next/prev navigation, circular loop terminations, and implementation of LRU cache structures.",
    difficulty: "Intermediate",
    timeComplexity: "O(1) Bidirectional Delete, O(N) Traversal",
    spaceComplexity: "O(N)",
    subtopics: ["Two-Way Node Structure", "Circular Head-Tail Linkage", "LRU Cache Architecture", "Sentinel Dummy Nodes"],
  }),
  createTopic({
    topicId: "dsa-u3-list-algorithms",
    chapterId: "dsa-u3-c1",
    unitId: "dsa-u3",
    subjectId: "dsa",
    topicNumber: 3,
    title: "Linked List Reversal, Cycle Detection & Applications",
    summary: "Iterative and recursive three-pointer list reversal, Floyd's Tortoise and Hare cycle finding algorithm.",
    difficulty: "Intermediate",
    timeComplexity: "O(N)",
    spaceComplexity: "O(1)",
    subtopics: ["3-Pointer In-Place Reversal", "Floyd's Cycle Detection", "Finding Cycle Start Node", "Middle Element Two-Pointer"],
  }),

  // Unit 4 Topics
  createTopic({
    topicId: "dsa-u4-stack-fundamentals",
    chapterId: "dsa-u4-c1",
    unitId: "dsa-u4",
    subjectId: "dsa",
    topicNumber: 1,
    title: "Stack Operations & Implementations",
    summary: "LIFO protocol, push/pop/peek operations, stack overflow/underflow handling, and array vs dynamic node backings.",
    difficulty: "Beginner",
    timeComplexity: "O(1) All Operations",
    spaceComplexity: "O(N)",
    subtopics: ["LIFO Mechanism", "Dynamic Array Implementation", "Linked List Implementation", "Balanced Parentheses Check"],
  }),
  createTopic({
    topicId: "dsa-u4-expression-conversion",
    chapterId: "dsa-u4-c1",
    unitId: "dsa-u4",
    subjectId: "dsa",
    topicNumber: 2,
    title: "Expression Conversion & Evaluation (Infix, Postfix, Prefix)",
    summary: "Operator precedence, Shunting-Yard parsing algorithm, and stack evaluation of Reverse Polish Notation.",
    difficulty: "Intermediate",
    timeComplexity: "O(N)",
    spaceComplexity: "O(N)",
    subtopics: ["Infix to Postfix Conversion", "Postfix Evaluation Algorithm", "Operator Precedence & Associativity"],
  }),
  createTopic({
    topicId: "dsa-u4-queue-variants",
    chapterId: "dsa-u4-c1",
    unitId: "dsa-u4",
    subjectId: "dsa",
    topicNumber: 3,
    title: "Queue, Circular Queue, Deque & Priority Queue",
    summary: "FIFO queuing, circular modulo ring buffers, double-ended queues (deque), and binary heap priority queues.",
    difficulty: "Intermediate",
    timeComplexity: "O(1) Queue Ops, O(log N) Priority Queue",
    spaceComplexity: "O(N)",
    subtopics: ["FIFO Mechanics", "Circular Queue Modulo Math", "Double-Ended Queue (Deque)", "Priority Queue via Heaps"],
  }),

  // Unit 5 Topics
  createTopic({
    topicId: "dsa-u5-binary-tree-traversals",
    chapterId: "dsa-u5-c1",
    unitId: "dsa-u5",
    subjectId: "dsa",
    topicNumber: 1,
    title: "Binary Tree Terminology & Traversals",
    summary: "Hierarchical tree nodes, depth, height, diameter, recursive and iterative Preorder, Inorder, Postorder, and Level-Order BFS.",
    difficulty: "Intermediate",
    timeComplexity: "O(N)",
    spaceComplexity: "O(H) Call Stack",
    subtopics: ["Tree Properties (Height, Depth, Degree)", "DFS Traversals (Pre, In, Post)", "BFS Level-Order using Queue", "Morris Traversal O(1) Space"],
  }),
  createTopic({
    topicId: "dsa-u5-bst-operations",
    chapterId: "dsa-u5-c1",
    unitId: "dsa-u5",
    subjectId: "dsa",
    topicNumber: 2,
    title: "Binary Search Tree (BST) Operations",
    summary: "Binary Search Tree ordering invariant, O(log N) search, insertion, in-order predecessor/successor, and deletion cases.",
    difficulty: "Intermediate",
    timeComplexity: "O(H) = O(log N) Average, O(N) Skewed",
    spaceComplexity: "O(H)",
    subtopics: ["BST Invariant (Left < Root < Right)", "Search & Insert Algorithms", "3-Case Deletion (Leaf, One Child, Two Children)", "Inorder Successor"],
  }),
  createTopic({
    topicId: "dsa-u5-avl-trees",
    chapterId: "dsa-u5-c1",
    unitId: "dsa-u5",
    subjectId: "dsa",
    topicNumber: 3,
    title: "AVL Trees & Self-Balancing Rotations",
    summary: "Height-balanced binary search tree maintaining balance factor in {-1, 0, 1} via LL, RR, LR, and RL rotations.",
    difficulty: "Advanced",
    timeComplexity: "O(log N) Guaranteed",
    spaceComplexity: "O(N)",
    subtopics: ["Balance Factor Definition", "Single Rotations (LL and RR)", "Double Rotations (LR and RL)", "Guaranteed O(log N) Bounds"],
  }),
  createTopic({
    topicId: "dsa-u5-heaps-btree",
    chapterId: "dsa-u5-c1",
    unitId: "dsa-u5",
    subjectId: "dsa",
    topicNumber: 4,
    title: "Binary Heap, Min/Max Heap & B/B+ Trees",
    summary: "Complete binary tree heap representation in arrays, heapify up/down, and multi-way balanced B-Trees for database disk indexes.",
    difficulty: "Advanced",
    timeComplexity: "Heapify: O(log N), B-Tree Search: O(log_M N)",
    spaceComplexity: "O(N)",
    subtopics: ["Array Heap Indexing Formula", "Sift-Up and Sift-Down Routines", "B-Tree Node Structure & Splitting", "B+ Tree Disk Search Invariants"],
  }),

  // Unit 6 Topics
  createTopic({
    topicId: "dsa-u6-graph-representations",
    chapterId: "dsa-u6-c1",
    unitId: "dsa-u6",
    subjectId: "dsa",
    topicNumber: 1,
    title: "Graph Terminology & Representations",
    summary: "Vertices, edges, directed vs undirected graphs, weighted graphs, adjacency matrix vs adjacency list space-time trade-offs.",
    difficulty: "Intermediate",
    timeComplexity: "Matrix: O(V^2) Space, List: O(V + E) Space",
    spaceComplexity: "O(V + E)",
    subtopics: ["Adjacency Matrix O(1) Edge Lookup", "Adjacency List O(deg(V)) Traversal", "Weighted & Directed Edge Encodings"],
  }),
  createTopic({
    topicId: "dsa-u6-bfs-dfs-cycles",
    chapterId: "dsa-u6-c1",
    unitId: "dsa-u6",
    subjectId: "dsa",
    topicNumber: 2,
    title: "BFS, DFS, Connected Components & Cycle Detection",
    summary: "Queue-based BFS for shortest paths, recursion-based DFS, connected components, and cycle detection using visited state arrays.",
    difficulty: "Intermediate",
    timeComplexity: "O(V + E)",
    spaceComplexity: "O(V)",
    subtopics: ["BFS Shortest Path on Unweighted Graphs", "DFS Recursion & Discovery/Finish Times", "Cycle Detection in Directed Graphs", "Connected Components via BFS/DFS"],
  }),
  createTopic({
    topicId: "dsa-u6-topo-sort-mst",
    chapterId: "dsa-u6-c1",
    unitId: "dsa-u6",
    subjectId: "dsa",
    topicNumber: 3,
    title: "Topological Sort & Minimum Spanning Trees (Prim's & Kruskal's)",
    summary: "Directed Acyclic Graph dependency ordering (Kahn's algorithm), and greedy MST construction using Disjoint Set Union (DSU) and priority queues.",
    difficulty: "Advanced",
    timeComplexity: "Topo: O(V+E), Kruskal: O(E log E), Prim: O(E log V)",
    spaceComplexity: "O(V)",
    subtopics: ["Kahn's Indegree Algorithm", "Kruskal's Algorithm with DSU", "Prim's Greedy Priority Queue Algorithm", "Cut Property in Graphs"],
  }),
  createTopic({
    topicId: "dsa-u6-shortest-paths",
    chapterId: "dsa-u6-c1",
    unitId: "dsa-u6",
    subjectId: "dsa",
    topicNumber: 4,
    title: "Shortest Paths: Dijkstra, Bellman-Ford & Floyd-Warshall",
    summary: "Single-source greedy shortest path (Dijkstra), negative-weight edge handling (Bellman-Ford), and all-pairs shortest paths (Floyd-Warshall).",
    difficulty: "Advanced",
    timeComplexity: "Dijkstra: O((V+E) log V), Bellman-Ford: O(V*E), Floyd: O(V^3)",
    spaceComplexity: "O(V) to O(V^2)",
    subtopics: ["Dijkstra Relaxation Invariant", "Bellman-Ford Negative Cycle Detection", "Floyd-Warshall Dynamic Programming Matrix"],
  }),

  // Unit 7 Topics
  createTopic({
    topicId: "dsa-u7-greedy-divide-conquer",
    chapterId: "dsa-u7-c1",
    unitId: "dsa-u7",
    subjectId: "dsa",
    topicNumber: 1,
    title: "Greedy Algorithms & Divide and Conquer",
    summary: "Greedy choice property, local optimality proving global optimality (Activity Selection, Fractional Knapsack), and divide-and-conquer recurrences.",
    difficulty: "Intermediate",
    timeComplexity: "O(N log N)",
    spaceComplexity: "O(1) to O(N)",
    subtopics: ["Greedy Choice Property", "Optimal Substructure Proof", "Fractional Knapsack vs 0/1 Knapsack", "Master Theorem for Divide & Conquer"],
  }),
  createTopic({
    topicId: "dsa-u7-dynamic-programming",
    chapterId: "dsa-u7-c1",
    unitId: "dsa-u7",
    subjectId: "dsa",
    topicNumber: 2,
    title: "Dynamic Programming: Memoization vs Tabulation",
    summary: "Overlapping subproblems, top-down recursion with caching (memoization) vs bottom-up iterative table filling (tabulation).",
    difficulty: "Advanced",
    timeComplexity: "O(N) to O(N*W)",
    spaceComplexity: "O(N) with state reduction",
    subtopics: ["Top-Down Memoization Recursion", "Bottom-Up Tabulation Matrix", "State Space Reduction Optimization", "Fibonacci & Climbing Stairs DP"],
  }),
  createTopic({
    topicId: "dsa-u7-classic-dp-problems",
    chapterId: "dsa-u7-c1",
    unitId: "dsa-u7",
    subjectId: "dsa",
    topicNumber: 3,
    title: "Classic DP Patterns: Knapsack, LCS & LIS",
    summary: "Formulating state transitions for 0/1 Knapsack, Longest Common Subsequence, Longest Increasing Subsequence, and Matrix Chain Multiplication.",
    difficulty: "Advanced",
    timeComplexity: "O(N*W) or O(N*M)",
    spaceComplexity: "O(N*W) or O(N*M)",
    subtopics: ["0/1 Knapsack State Matrix", "Longest Common Subsequence (LCS)", "Longest Increasing Subsequence (LIS)", "Edit Distance Transition Formula"],
  }),
  createTopic({
    topicId: "dsa-u7-backtracking-branch-bound",
    chapterId: "dsa-u7-c1",
    unitId: "dsa-u7",
    subjectId: "dsa",
    topicNumber: 4,
    title: "Backtracking & Branch and Bound",
    summary: "Systematic state-space tree traversal, constraint satisfaction, pruning non-viable solution subtrees (N-Queens, Sudoku, Subset Sum).",
    difficulty: "Advanced",
    timeComplexity: "Exponential O(2^N) or O(N!) with Pruning",
    spaceComplexity: "O(N) Call Stack",
    subtopics: ["State-Space Search Tree", "Pruning Invalid Paths Early", "N-Queens Solution Formulation", "Branch and Bound Cost Bounding"],
  }),
];
