import { createTopic } from "./builder.js";

export const ML_AI_UNITS = [
  {
    unitId: "ml-u1",
    subjectId: "ml-ai",
    unitNumber: 1,
    title: "Unit 1 — AI & ML Fundamentals",
    description: "Definitions of AI, Machine Learning vs Deep Learning, Supervised vs Unsupervised vs Reinforcement learning paradigms.",
    learningObjectives: [
      "Understand the taxonomy of Artificial Intelligence, ML, and Deep Learning",
      "Contrast Supervised Learning (labeled data) with Unsupervised Learning (unlabeled patterns)",
      "Explain Reinforcement Learning agent-environment reward feedback loops",
      "Formulate the machine learning lifecycle: data collection, training, inference, and monitoring",
    ],
    difficulty: "Beginner",
    estimatedHours: 3.0,
    prerequisites: ["Basic Programming", "High School Mathematics"],
    practiceQuestionsCount: 15,
    quizQuestionsCount: 10,
    order: 1,
  },
  {
    unitId: "ml-u2",
    subjectId: "ml-ai",
    unitNumber: 2,
    title: "Unit 2 — Python for Machine Learning",
    description: "Vectorized computations with NumPy, tabular data manipulation with Pandas, visualizations with Matplotlib, and feature engineering pipelines.",
    learningObjectives: [
      "Perform fast vectorized matrix operations and broadcasting using NumPy arrays",
      "Filter, aggregate, and transform tabular DataFrames using Pandas",
      "Handle missing data (imputation), categorical encoding (One-Hot, Ordinal), and outlier detection",
      "Apply feature scaling (StandardScaler z-score vs MinMaxScaler normalization)",
    ],
    difficulty: "Intermediate",
    estimatedHours: 4.5,
    prerequisites: ["Unit 1 — AI & ML Fundamentals"],
    practiceQuestionsCount: 18,
    quizQuestionsCount: 12,
    order: 2,
  },
  {
    unitId: "ml-u3",
    subjectId: "ml-ai",
    unitNumber: 3,
    title: "Unit 3 — Supervised Learning Algorithms",
    description: "Regression and classification: Linear Regression (OLS, gradient descent), Logistic Regression (sigmoid), KNN, Decision Trees, Random Forests, SVMs, and Naive Bayes.",
    learningObjectives: [
      "Derive cost functions (Mean Squared Error, Binary Cross-Entropy) and Gradient Descent updates",
      "Understand Decision Tree splitting criteria (Gini Impurity, Information Gain / Entropy)",
      "Combine decision trees into ensemble Random Forests via bagging and feature subsampling",
      "Formulate Support Vector Machines (maximal margin hyperplanes, kernel trick) and Bayes Theorem classifiers",
    ],
    difficulty: "Intermediate",
    estimatedHours: 6.0,
    prerequisites: ["Unit 2 — Python for ML"],
    practiceQuestionsCount: 22,
    quizQuestionsCount: 15,
    order: 3,
  },
  {
    unitId: "ml-u4",
    subjectId: "ml-ai",
    unitNumber: 4,
    title: "Unit 4 — Unsupervised Learning & Dimensionality Reduction",
    description: "Clustering algorithms (K-Means centroids, Hierarchical agglomerative clustering), and Principal Component Analysis (PCA) eigenvalue decomposition.",
    learningObjectives: [
      "Implement the iterative K-Means clustering algorithm and choose optimal K via the Elbow Method",
      "Construct agglomerative hierarchical clustering dendrograms with linkage criteria",
      "Reduce high-dimensional feature spaces using Principal Component Analysis (PCA)",
      "Analyze covariance matrices and project data onto maximal variance eigenvectors",
    ],
    difficulty: "Intermediate",
    estimatedHours: 4.5,
    prerequisites: ["Unit 3 — Supervised Learning"],
    practiceQuestionsCount: 18,
    quizQuestionsCount: 12,
    order: 4,
  },
  {
    unitId: "ml-u5",
    subjectId: "ml-ai",
    unitNumber: 5,
    title: "Unit 5 — Model Evaluation & Validation",
    description: "Train/test splits, K-Fold cross-validation, Confusion Matrix, Accuracy, Precision, Recall, F1-Score, ROC-AUC, and the Bias-Variance trade-off.",
    learningObjectives: [
      "Evaluate classification models using Precision, Recall, F1-Score, and ROC-AUC curves",
      "Handle class imbalance using Stratified K-Fold and cost-sensitive weighting",
      "Diagnose Overfitting (High Variance) vs Underfitting (High Bias) via learning curves",
      "Apply regularization (L1 Lasso for feature selection, L2 Ridge for weight shrinking)",
    ],
    difficulty: "Intermediate",
    estimatedHours: 4.0,
    prerequisites: ["Unit 3 — Supervised Learning"],
    practiceQuestionsCount: 20,
    quizQuestionsCount: 12,
    order: 5,
  },
  {
    unitId: "ml-u6",
    subjectId: "ml-ai",
    unitNumber: 6,
    title: "Unit 6 — Deep Learning & Generative AI",
    description: "Artificial Neural Networks (ANN), backpropagation, CNNs for computer vision, RNNs for sequences, Transformers self-attention, LLMs, and prompt engineering.",
    learningObjectives: [
      "Trace forward propagation, activation functions (ReLU, Sigmoid, Softmax), and backpropagation gradient flow",
      "Understand Convolutional Neural Networks (CNN) filters, feature maps, and max pooling",
      "Master the Transformer architecture: Scaled Dot-Product Self-Attention and multi-head attention",
      "Apply Generative AI, Large Language Models (LLMs), Prompt Engineering, and RAG architectures",
    ],
    difficulty: "Advanced",
    estimatedHours: 6.5,
    prerequisites: ["Unit 5 — Model Evaluation"],
    practiceQuestionsCount: 25,
    quizQuestionsCount: 15,
    order: 6,
  },
];

export const ML_AI_CHAPTERS = ML_AI_UNITS.map((u) => ({
  chapterId: `${u.unitId}-c1`,
  unitId: u.unitId,
  subjectId: "ml-ai",
  chapterNumber: 1,
  title: u.title.replace(/Unit \d+ — /, ""),
  description: u.description,
  order: u.unitNumber,
}));

export const ML_AI_TOPICS = [
  // Unit 1 Topics
  createTopic({
    topicId: "ml-u1-intro-taxonomies",
    chapterId: "ml-u1-c1",
    unitId: "ml-u1",
    subjectId: "ml-ai",
    topicNumber: 1,
    title: "AI, Machine Learning & Deep Learning Overview",
    summary: "Taxonomy of artificial intelligence, rule-based systems vs statistical machine learning, and deep multi-layer neural network representations.",
    difficulty: "Beginner",
    timeComplexity: "O(1)",
    spaceComplexity: "O(1)",
    subtopics: ["AI vs ML vs Deep Learning Hierarchy", "Rule-Based Systems vs Learning from Data", "General AI vs Narrow AI", "End-to-End Machine Learning Pipeline"],
  }),
  createTopic({
    topicId: "ml-u1-learning-paradigms",
    chapterId: "ml-u1-c1",
    unitId: "ml-u1",
    subjectId: "ml-ai",
    topicNumber: 2,
    title: "Supervised, Unsupervised & Reinforcement Learning",
    summary: "Labeled regression/classification tasks, finding hidden structures in unlabeled data, and agent policy reward maximization in RL.",
    difficulty: "Beginner",
    timeComplexity: "O(1)",
    spaceComplexity: "O(1)",
    subtopics: ["Supervised Learning (Regression vs Classification)", "Unsupervised Learning (Clustering, Dimensionality Reduction)", "Reinforcement Learning (Agent, Environment, Reward)", "Semi-Supervised & Self-Supervised Paradigms"],
  }),

  // Unit 2 Topics
  createTopic({
    topicId: "ml-u2-numpy-pandas",
    chapterId: "ml-u2-c1",
    unitId: "ml-u2",
    subjectId: "ml-ai",
    topicNumber: 1,
    title: "NumPy Arrays, Vectorization & Pandas DataFrames",
    summary: "C-contiguous NumPy arrays, vectorized arithmetic without Python loops, broadcasting rules, and Pandas DataFrame filtering, groupby, and joins.",
    difficulty: "Intermediate",
    timeComplexity: "O(N) Vectorized C-Speed",
    spaceComplexity: "O(Data Size)",
    subtopics: ["NumPy n-dimensional Array Creation & Indexing", "Vectorized Array Broadcasting Rules", "Pandas DataFrames, Series & Missing Value Handling", "GroupBy Aggregations & Pivot Tables"],
  }),
  createTopic({
    topicId: "ml-u2-preprocessing-feature-eng",
    chapterId: "ml-u2-c1",
    unitId: "ml-u2",
    subjectId: "ml-ai",
    topicNumber: 2,
    title: "Data Preprocessing, Cleaning & Feature Engineering",
    summary: "Missing value imputation, One-Hot vs Ordinal encoding, z-score standardization (StandardScaler), Min-Max normalization, and feature creation.",
    difficulty: "Intermediate",
    timeComplexity: "O(N * Features)",
    spaceComplexity: "O(N * Features)",
    subtopics: ["Handling Missing Data (Mean, Median, KNN Imputation)", "Categorical Encoding (One-Hot, Target, Ordinal)", "StandardScaler (Z-Score) vs MinMaxScaler", "Feature Selection & Interaction Terms"],
  }),

  // Unit 3 Topics
  createTopic({
    topicId: "ml-u3-regression-gradient-descent",
    chapterId: "ml-u3-c1",
    unitId: "ml-u3",
    subjectId: "ml-ai",
    topicNumber: 1,
    title: "Linear & Logistic Regression with Gradient Descent",
    summary: "Ordinary Least Squares (OLS), Mean Squared Error (MSE), Sigmoid activation, Binary Cross-Entropy loss, and Batch/Stochastic Gradient Descent.",
    difficulty: "Intermediate",
    timeComplexity: "O(Iterations * N * Features)",
    spaceComplexity: "O(Weights)",
    subtopics: ["Linear Regression Hypothesis & MSE Loss", "Gradient Descent Step Updates & Learning Rate Alpha", "Logistic Regression Sigmoid & Log-Loss", "Decision Boundaries & Probability Outputs"],
  }),
  createTopic({
    topicId: "ml-u3-trees-ensembles-svm",
    chapterId: "ml-u3-c1",
    unitId: "ml-u3",
    subjectId: "ml-ai",
    topicNumber: 2,
    title: "Decision Trees, Random Forests, SVM & Naive Bayes",
    summary: "Recursive binary splitting (Gini Impurity, Entropy), Bagging ensemble Random Forests, Support Vector maximal margin hyperplanes, and Naive Bayes.",
    difficulty: "Intermediate",
    timeComplexity: "Tree Predict: O(Depth), Forest: O(Trees * Depth)",
    spaceComplexity: "O(Tree Nodes)",
    subtopics: ["Gini Impurity & Information Gain Splitting", "Random Forest Bootstrap Aggregating (Bagging)", "Support Vector Machines & Kernel Trick (RBF)", "Naive Bayes Conditional Independence Assumption"],
  }),

  // Unit 4 Topics
  createTopic({
    topicId: "ml-u4-kmeans-hierarchical",
    chapterId: "ml-u4-c1",
    unitId: "ml-u4",
    subjectId: "ml-ai",
    topicNumber: 1,
    title: "Clustering Algorithms: K-Means & Hierarchical",
    summary: "Iterative centroid updates in K-Means, inertia distortion, the Elbow Method, Silhouette scores, and agglomerative clustering dendrograms.",
    difficulty: "Intermediate",
    timeComplexity: "K-Means: O(Iterations * K * N * D)",
    spaceComplexity: "O(K * D + N)",
    subtopics: ["K-Means Expectation-Maximization Routine", "Optimal K Selection via Elbow & Silhouette Analysis", "Agglomerative Hierarchical Clustering Linkage Criteria", "Dendrograms & Cluster Cutoffs"],
  }),
  createTopic({
    topicId: "ml-u4-pca-dimensionality-reduction",
    chapterId: "ml-u4-c1",
    unitId: "ml-u4",
    subjectId: "ml-ai",
    topicNumber: 2,
    title: "Principal Component Analysis (PCA) & Dimensionality Reduction",
    summary: "Curse of dimensionality, data covariance matrix, eigenvectors, eigenvalues, and projecting data onto orthogonal principal components.",
    difficulty: "Advanced",
    timeComplexity: "O(D^3) Eigendecomposition",
    spaceComplexity: "O(D^2)",
    subtopics: ["Curse of Dimensionality in Machine Learning", "Covariance Matrix Computation", "Eigenvalues & Explained Variance Ratio", "Projecting High-Dimensional Data to 2D/3D"],
  }),

  // Unit 5 Topics
  createTopic({
    topicId: "ml-u5-evaluation-metrics",
    chapterId: "ml-u5-c1",
    unitId: "ml-u5",
    subjectId: "ml-ai",
    topicNumber: 1,
    title: "Model Evaluation: Confusion Matrix, Precision, Recall & ROC-AUC",
    summary: "True/False Positives/Negatives, Precision vs Recall trade-offs, F1-Score harmonic mean, ROC curves, and Area Under the Curve (AUC).",
    difficulty: "Intermediate",
    timeComplexity: "O(N) Evaluation",
    spaceComplexity: "O(1)",
    subtopics: ["Confusion Matrix Anatomy (TP, FP, TN, FN)", "Precision vs Recall Trade-Off Curves", "F1-Score Harmonic Mean Formula", "Receiver Operating Characteristic (ROC) & AUC"],
  }),
  createTopic({
    topicId: "ml-u5-bias-variance-cv",
    chapterId: "ml-u5-c1",
    unitId: "ml-u5",
    subjectId: "ml-ai",
    topicNumber: 2,
    title: "Overfitting, Underfitting, Bias-Variance Trade-Off & Cross-Validation",
    summary: "High Bias (Underfitting) vs High Variance (Overfitting), K-Fold Cross-Validation, and L1 Lasso / L2 Ridge regularization.",
    difficulty: "Intermediate",
    timeComplexity: "O(K * Train Time)",
    spaceComplexity: "O(Model)",
    subtopics: ["Bias-Variance Decomposition", "Diagnosing Overfitting via Train vs Validation Curves", "K-Fold & Stratified K-Fold Cross-Validation", "L1 Lasso vs L2 Ridge Regularization Penalties"],
  }),

  // Unit 6 Topics
  createTopic({
    topicId: "ml-u6-neural-networks-cnn-rnn",
    chapterId: "ml-u6-c1",
    unitId: "ml-u6",
    subjectId: "ml-ai",
    topicNumber: 1,
    title: "Neural Networks (ANN, CNN, RNN) & Backpropagation",
    summary: "Perceptrons, forward propagation, activation functions (ReLU, Sigmoid), backpropagation chain rule, CNN spatial convolutions, and RNN sequential memory.",
    difficulty: "Advanced",
    timeComplexity: "O(Weights * Epochs)",
    spaceComplexity: "O(Model Parameters)",
    subtopics: ["Artificial Neural Networks & Activation Functions", "Backpropagation Calculus via the Chain Rule", "CNN Convolutions, Kernels & Max Pooling Layers", "Recurrent Neural Networks (RNN) & Vanishing Gradients"],
  }),
  createTopic({
    topicId: "ml-u6-transformers-llm-genai",
    chapterId: "ml-u6-c1",
    unitId: "ml-u6",
    subjectId: "ml-ai",
    topicNumber: 2,
    title: "Transformers, Large Language Models (LLMs) & Generative AI",
    summary: "Attention is All You Need: self-attention dot products, multi-head attention, autoregressive decoder models (GPT), Prompt Engineering, and RAG architectures.",
    difficulty: "Advanced",
    timeComplexity: "O(Sequence_Length^2) Self-Attention",
    spaceComplexity: "O(Parameters + KV Cache)",
    subtopics: ["Scaled Dot-Product Self-Attention Formula", "Transformer Encoder-Decoder & Decoder-Only LLMs", "Generative AI, Temperature & Top-P Sampling", "Prompt Engineering & Retrieval-Augmented Generation (RAG)"],
  }),
];
