import { createTopic } from "./builder.js";

export const OOPS_UNITS = [
  {
    unitId: "oops-u1",
    subjectId: "oops",
    unitNumber: 1,
    title: "Unit 1 — OOP Fundamentals",
    description: "Classes, objects, encapsulation, abstraction, inheritance, compile/runtime polymorphism, constructors, destructors, and access modifiers.",
    learningObjectives: [
      "Instantiate classes and understand memory heap vs stack allocation",
      "Protect internal invariant state via encapsulation and access modifiers (private, protected, public)",
      "Model real-world domains using Single, Multilevel, and Hierarchical Inheritance",
      "Contrast compile-time polymorphism with dynamic method dispatch (vtable)",
    ],
    difficulty: "Beginner",
    estimatedHours: 3.5,
    prerequisites: ["Basic Programming Syntax"],
    practiceQuestionsCount: 15,
    quizQuestionsCount: 10,
    order: 1,
  },
  {
    unitId: "oops-u2",
    subjectId: "oops",
    unitNumber: 2,
    title: "Unit 2 — Advanced OOP & Relationships",
    description: "Method overloading vs overriding, pure virtual interfaces, abstract classes, and object relationships (Association, Aggregation, Composition).",
    learningObjectives: [
      "Differentiate method overloading from runtime virtual method overriding",
      "Design abstract classes and pure interface contracts",
      "Differentiate weak Association, Aggregation ('has-a'), and tight Composition ('owns-a')",
      "Avoid diamond inheritance issues using virtual inheritance",
    ],
    difficulty: "Intermediate",
    estimatedHours: 4.0,
    prerequisites: ["Unit 1 — OOP Fundamentals"],
    practiceQuestionsCount: 18,
    quizQuestionsCount: 12,
    order: 2,
  },
  {
    unitId: "oops-u3",
    subjectId: "oops",
    unitNumber: 3,
    title: "Unit 3 — SOLID Principles",
    description: "Robert C. Martin's 5 architectural principles: Single Responsibility, Open-Closed, Liskov Substitution, Interface Segregation, and Dependency Inversion.",
    learningObjectives: [
      "Enforce Single Responsibility Principle (SRP) to eliminate coupled change reasons",
      "Apply Open/Closed Principle (OCP) using polymorphism and extension points",
      "Preserve behavioral subtyping under Liskov Substitution Principle (LSP)",
      "Decouple high-level modules from low-level details using Dependency Inversion (DIP)",
    ],
    difficulty: "Advanced",
    estimatedHours: 4.5,
    prerequisites: ["Unit 2 — Advanced OOP"],
    practiceQuestionsCount: 20,
    quizQuestionsCount: 15,
    order: 3,
  },
  {
    unitId: "oops-u4",
    subjectId: "oops",
    unitNumber: 4,
    title: "Unit 4 — Enterprise Design Patterns",
    description: "Gang of Four (GoF) design patterns: Creational (Singleton, Factory, Builder), Structural (Adapter), Behavioral (Observer, Strategy), and Architectural (MVC).",
    learningObjectives: [
      "Implement thread-safe double-checked locking Singletons",
      "Decouple concrete instantiation using Factory Method and Abstract Factory",
      "Construct complex immutable objects with the Builder Pattern",
      "Implement event-driven systems using Observer and behavioral Strategy interchangeability",
    ],
    difficulty: "Advanced",
    estimatedHours: 5.0,
    prerequisites: ["Unit 3 — SOLID Principles"],
    practiceQuestionsCount: 22,
    quizQuestionsCount: 15,
    order: 4,
  },
];

export const OOPS_CHAPTERS = OOPS_UNITS.map((u) => ({
  chapterId: `${u.unitId}-c1`,
  unitId: u.unitId,
  subjectId: "oops",
  chapterNumber: 1,
  title: u.title.replace(/Unit \d+ — /, ""),
  description: u.description,
  order: u.unitNumber,
}));

export const OOPS_TOPICS = [
  // Unit 1 Topics
  createTopic({
    topicId: "oops-u1-classes-objects",
    chapterId: "oops-u1-c1",
    unitId: "oops-u1",
    subjectId: "oops",
    topicNumber: 1,
    title: "Classes, Objects & Encapsulation",
    summary: "Blueprints vs memory instances, getter/setter data hiding, access modifiers, constructors, copy constructors, and destructors.",
    difficulty: "Beginner",
    timeComplexity: "O(1)",
    spaceComplexity: "O(Instance Size)",
    subtopics: ["Class Blueprint vs Object Memory Layout", "Private, Protected & Public Visibility", "Default, Parameterized & Copy Constructors", "Destructor Resource Cleanup (RAII)"],
  }),
  createTopic({
    topicId: "oops-u1-inheritance-polymorphism",
    chapterId: "oops-u1-c1",
    unitId: "oops-u1",
    subjectId: "oops",
    topicNumber: 2,
    title: "Inheritance, Polymorphism & Virtual Tables",
    summary: "Code reuse via class hierarchies, compile-time overloading, runtime method overriding, and virtual method table (vtable) dispatch.",
    difficulty: "Intermediate",
    timeComplexity: "O(1) vtable lookup",
    spaceComplexity: "O(1)",
    subtopics: ["Single, Multiple & Multilevel Inheritance", "Compile-Time vs Runtime Polymorphism", "Virtual Functions & vptr/vtable Mechanics", "Object Slicing in Base Conversions"],
  }),

  // Unit 2 Topics
  createTopic({
    topicId: "oops-u2-abstract-interfaces",
    chapterId: "oops-u2-c1",
    unitId: "oops-u2",
    subjectId: "oops",
    topicNumber: 1,
    title: "Abstract Classes vs Interfaces",
    summary: "Pure virtual contracts, abstract classes with shared state vs pure interfaces with method signatures, and default interface methods.",
    difficulty: "Intermediate",
    timeComplexity: "O(1)",
    spaceComplexity: "O(1)",
    subtopics: ["Pure Virtual Functions (= 0 syntax)", "Abstract Class vs Interface Differences", "Multiple Interface Implementation", "Diamond Problem & Virtual Base Classes"],
  }),
  createTopic({
    topicId: "oops-u2-composition-aggregation",
    chapterId: "oops-u2-c1",
    unitId: "oops-u2",
    subjectId: "oops",
    topicNumber: 2,
    title: "Object Relationships: Composition, Aggregation & Association",
    summary: "Favoring composition over inheritance, lifecycle dependency ('owns-a' vs 'has-a'), and coupling reduction in large software.",
    difficulty: "Intermediate",
    timeComplexity: "O(1)",
    spaceComplexity: "O(N)",
    subtopics: ["Association (Loose Peer Relationship)", "Aggregation (Has-A with Independent Lifecycle)", "Composition (Owns-A with Shared Destruction)", "Why Composition Beats Deep Inheritance"],
  }),

  // Unit 3 Topics
  createTopic({
    topicId: "oops-u3-solid-srp-ocp",
    chapterId: "oops-u3-c1",
    unitId: "oops-u3",
    subjectId: "oops",
    topicNumber: 1,
    title: "SOLID: Single Responsibility & Open/Closed Principles",
    summary: "Single reason to change rule, and extending software functionality by adding new code without modifying tested existing modules.",
    difficulty: "Advanced",
    timeComplexity: "O(1)",
    spaceComplexity: "O(1)",
    subtopics: ["Single Responsibility Principle (SRP) Violations", "Refactoring God Classes into Cohesive Units", "Open/Closed Principle (OCP) via Polymorphism", "Pluggable Architecture Patterns"],
  }),
  createTopic({
    topicId: "oops-u3-solid-lsp-isp-dip",
    chapterId: "oops-u3-c1",
    unitId: "oops-u3",
    subjectId: "oops",
    topicNumber: 2,
    title: "SOLID: Liskov Substitution, Interface Segregation & Dependency Inversion",
    summary: "Substitutability invariants (Square-Rectangle problem), fat interface fragmentation, and programming to abstractions via Dependency Injection.",
    difficulty: "Advanced",
    timeComplexity: "O(1)",
    spaceComplexity: "O(1)",
    subtopics: ["Liskov Substitution Principle (LSP) Pre/Post-Conditions", "Interface Segregation Principle (ISP) Lean Contracts", "Dependency Inversion Principle (DIP)", "Inversion of Control (IoC) & Dependency Injection"],
  }),

  // Unit 4 Topics
  createTopic({
    topicId: "oops-u4-creational-patterns",
    chapterId: "oops-u4-c1",
    unitId: "oops-u4",
    subjectId: "oops",
    topicNumber: 1,
    title: "Creational Patterns: Singleton, Factory & Builder",
    summary: "Thread-safe Singleton instances, Factory method encapsulation, Abstract Factory families, and fluent step-by-step Builder patterns.",
    difficulty: "Advanced",
    timeComplexity: "O(1)",
    spaceComplexity: "O(1)",
    subtopics: ["Thread-Safe Singleton with Double-Checked Locking", "Factory Method vs Abstract Factory", "Builder Pattern for Complex Immutable Objects", "Prototype Object Cloning"],
  }),
  createTopic({
    topicId: "oops-u4-structural-behavioral",
    chapterId: "oops-u4-c1",
    unitId: "oops-u4",
    subjectId: "oops",
    topicNumber: 2,
    title: "Structural & Behavioral Patterns: Adapter, Observer, Strategy & MVC",
    summary: "Incompatible interface bridging (Adapter), pub-sub event notifications (Observer), runtime algorithm swapping (Strategy), and MVC architecture.",
    difficulty: "Advanced",
    timeComplexity: "O(1)",
    spaceComplexity: "O(N) Observers",
    subtopics: ["Adapter Pattern Wrapper Architecture", "Observer Pattern Pub-Sub Decoupling", "Strategy Pattern Dynamic Behavioral Injection", "Model-View-Controller (MVC) Separation of Concerns"],
  }),
];
