import { createTopic } from "./builder.js";

export const OS_UNITS = [
  {
    unitId: "os-u1",
    subjectId: "os",
    unitNumber: 1,
    title: "Unit 1 — OS Fundamentals",
    description: "Operating system roles, monolithic vs microkernel architectures, system calls, and dual-mode CPU operation.",
    learningObjectives: [
      "Understand OS as an extended machine and resource allocator",
      "Explain User Mode vs Kernel Mode dual-mode hardware enforcement",
      "Trace system call execution and interrupt handling mechanisms",
      "Compare monolithic kernels (Linux) with microkernels (Mach, QNX)",
    ],
    difficulty: "Beginner",
    estimatedHours: 3.0,
    prerequisites: ["Computer Organization Basics"],
    practiceQuestionsCount: 12,
    quizQuestionsCount: 10,
    order: 1,
  },
  {
    unitId: "os-u2",
    subjectId: "os",
    unitNumber: 2,
    title: "Unit 2 — Processes & Threads",
    description: "Process states, Process Control Block (PCB), context switching, user/kernel threads, and Inter-Process Communication (IPC).",
    learningObjectives: [
      "Model process lifecycles (New, Ready, Running, Waiting, Terminated)",
      "Analyze Process Control Block (PCB) attributes and context switch overhead",
      "Contrast processes with lightweight threads and kernel thread models",
      "Implement IPC via shared memory, pipes, message queues, and sockets",
    ],
    difficulty: "Intermediate",
    estimatedHours: 4.0,
    prerequisites: ["Unit 1 — OS Fundamentals"],
    practiceQuestionsCount: 15,
    quizQuestionsCount: 12,
    order: 2,
  },
  {
    unitId: "os-u3",
    subjectId: "os",
    unitNumber: 3,
    title: "Unit 3 — CPU Scheduling",
    description: "Preemptive vs non-preemptive scheduling: FCFS, SJF, SRTF, Priority, Round Robin, Multilevel Queue, and MLFQ.",
    learningObjectives: [
      "Calculate Waiting Time, Turnaround Time, and Response Time metrics",
      "Simulate non-preemptive FCFS and optimal Shortest Job First (SJF)",
      "Implement Round Robin time-quantum slicing and analyze context switch cost",
      "Evaluate Multilevel Feedback Queue (MLFQ) priority aging heuristics",
    ],
    difficulty: "Intermediate",
    estimatedHours: 4.5,
    prerequisites: ["Unit 2 — Processes & Threads"],
    practiceQuestionsCount: 18,
    quizQuestionsCount: 12,
    order: 3,
  },
  {
    unitId: "os-u4",
    subjectId: "os",
    unitNumber: 4,
    title: "Unit 4 — Synchronization & Deadlocks",
    description: "Race conditions, critical sections, Mutexes, counting semaphores, classic synchronization problems, and Banker's Algorithm.",
    learningObjectives: [
      "Identify race conditions in shared mutable memory access",
      "Enforce mutual exclusion, progress, and bounded waiting criteria",
      "Solve Producer-Consumer, Readers-Writers, and Dining Philosophers problems",
      "Analyze the 4 Coffman conditions, Banker's avoidance, and deadlock detection",
    ],
    difficulty: "Advanced",
    estimatedHours: 5.5,
    prerequisites: ["Unit 2 — Threads"],
    practiceQuestionsCount: 22,
    quizQuestionsCount: 15,
    order: 4,
  },
  {
    unitId: "os-u5",
    subjectId: "os",
    unitNumber: 5,
    title: "Unit 5 — Memory Management",
    description: "Paging, segmentation, Translation Lookaside Buffers (TLB), virtual memory, demand paging, and page replacement algorithms.",
    learningObjectives: [
      "Calculate physical address translation from logical addresses using Page Tables",
      "Assess TLB hit ratios and Effective Memory Access Time (EMAT)",
      "Analyze internal vs external fragmentation and segmentation mechanics",
      "Evaluate FIFO, Least Recently Used (LRU), and Optimal Page Replacement policies",
    ],
    difficulty: "Advanced",
    estimatedHours: 5.0,
    prerequisites: ["Unit 1 — OS Fundamentals"],
    practiceQuestionsCount: 20,
    quizQuestionsCount: 15,
    order: 5,
  },
  {
    unitId: "os-u6",
    subjectId: "os",
    unitNumber: 6,
    title: "Unit 6 — File & Storage Management",
    description: "File systems, directory structures, inode allocation, disk scheduling algorithms (FCFS, SSTF, SCAN, LOOK), and RAID levels.",
    learningObjectives: [
      "Understand file system metadata, inodes, and file allocation methods (contiguous, linked, indexed)",
      "Calculate disk head movements for FCFS, SSTF, SCAN, C-SCAN, and LOOK",
      "Compare RAID 0, 1, 5, 6, and 10 redundancy and throughput profiles",
    ],
    difficulty: "Intermediate",
    estimatedHours: 4.0,
    prerequisites: ["Unit 5 — Memory Management"],
    practiceQuestionsCount: 15,
    quizQuestionsCount: 10,
    order: 6,
  },
];

export const OS_CHAPTERS = OS_UNITS.map((u) => ({
  chapterId: `${u.unitId}-c1`,
  unitId: u.unitId,
  subjectId: "os",
  chapterNumber: 1,
  title: u.title.replace(/Unit \d+ — /, ""),
  description: u.description,
  order: u.unitNumber,
}));

export const OS_TOPICS = [
  // Unit 1 Topics
  createTopic({
    topicId: "os-u1-intro-kernel",
    chapterId: "os-u1-c1",
    unitId: "os-u1",
    subjectId: "os",
    topicNumber: 1,
    title: "Operating System Architecture & Kernel Types",
    summary: "Hardware abstraction, resource management, monolithic vs microkernel designs, and dual-mode CPU security.",
    difficulty: "Beginner",
    timeComplexity: "O(1)",
    spaceComplexity: "O(1)",
    subtopics: ["Dual-Mode Operation (User Mode vs Kernel Mode)", "Monolithic vs Microkernel Architecture", "Kernel Space vs User Space", "Privileged CPU Instructions"],
  }),
  createTopic({
    topicId: "os-u1-system-calls",
    chapterId: "os-u1-c1",
    unitId: "os-u1",
    subjectId: "os",
    topicNumber: 2,
    title: "System Calls, OS Services & Interrupts",
    summary: "Software interrupts, trap handlers, system call dispatch table, and POSIX standard APIs (fork, exec, read, write).",
    difficulty: "Beginner",
    timeComplexity: "O(1)",
    spaceComplexity: "O(1)",
    subtopics: ["System Call Invocation Sequence", "Trap Mechanism & Hardware Interrupts", "System Call Dispatch Table", "Common POSIX System Calls"],
  }),

  // Unit 2 Topics
  createTopic({
    topicId: "os-u2-process-lifecycle",
    chapterId: "os-u2-c1",
    unitId: "os-u2",
    subjectId: "os",
    topicNumber: 1,
    title: "Process States, PCB & Context Switching",
    summary: "Process Control Block (PCB) attributes, state transitions (Ready, Running, Blocked), and context switch CPU register dumping.",
    difficulty: "Intermediate",
    timeComplexity: "O(1)",
    spaceComplexity: "O(1)",
    subtopics: ["5-State Process Lifecycle", "PCB Structure (Registers, PID, State, Limits)", "Context Switching Overhead", "CPU vs I/O Bound Processes"],
  }),
  createTopic({
    topicId: "os-u2-threads-ipc",
    chapterId: "os-u2-c1",
    unitId: "os-u2",
    subjectId: "os",
    topicNumber: 2,
    title: "Threads, Multithreading Models & IPC",
    summary: "Thread stack vs process memory sharing, 1:1 vs M:N thread models, and IPC via Shared Memory, Pipes, and Sockets.",
    difficulty: "Intermediate",
    timeComplexity: "O(1) to O(N)",
    spaceComplexity: "O(N)",
    subtopics: ["Process vs Thread Memory Comparison", "User-Level vs Kernel-Level Threads", "Shared Memory vs Message Passing IPC", "Anonymous and Named Pipes (FIFOs)"],
  }),

  // Unit 3 Topics
  createTopic({
    topicId: "os-u3-scheduling-metrics",
    chapterId: "os-u3-c1",
    unitId: "os-u3",
    subjectId: "os",
    topicNumber: 1,
    title: "CPU Scheduling Metrics & Algorithms (FCFS, SJF, SRTF)",
    summary: "Gantt chart evaluation of First-Come First-Served, Shortest Job First, and preemptive Shortest Remaining Time First.",
    difficulty: "Intermediate",
    timeComplexity: "O(N log N)",
    spaceComplexity: "O(N)",
    subtopics: ["Turnaround, Waiting & Response Time Formulas", "FCFS Convoy Effect", "SJF Provable Optimality", "SRTF Preemptive Gantt Charts"],
  }),
  createTopic({
    topicId: "os-u3-round-robin-mlfq",
    chapterId: "os-u3-c1",
    unitId: "os-u3",
    subjectId: "os",
    topicNumber: 2,
    title: "Round Robin, Priority Scheduling & MLFQ",
    summary: "Time-quantum time sharing, priority inversion with aging, and adaptive Multilevel Feedback Queue (MLFQ) scheduling.",
    difficulty: "Intermediate",
    timeComplexity: "O(1) Scheduling Decision",
    spaceComplexity: "O(N)",
    subtopics: ["Round Robin Time Slice Tuning", "Starvation & Priority Aging", "Multilevel Queue Separation", "MLFQ Adaptive Priority Demotion"],
  }),

  // Unit 4 Topics
  createTopic({
    topicId: "os-u4-critical-section-mutex",
    chapterId: "os-u4-c1",
    unitId: "os-u4",
    subjectId: "os",
    topicNumber: 1,
    title: "Critical Section, Race Conditions & Mutex/Semaphores",
    summary: "Race conditions, Peterson's algorithm, hardware atomic instructions (CAS), Mutex locks, and Counting vs Binary Semaphores.",
    difficulty: "Advanced",
    timeComplexity: "O(1)",
    spaceComplexity: "O(1)",
    subtopics: ["Mutual Exclusion, Progress & Bounded Waiting", "Peterson's Algorithm Invariant", "Compare-And-Swap (CAS) Hardware Atomics", "Semaphores wait() and signal() Primitives"],
  }),
  createTopic({
    topicId: "os-u4-sync-problems",
    chapterId: "os-u4-c1",
    unitId: "os-u4",
    subjectId: "os",
    topicNumber: 2,
    title: "Classic Synchronization Problems & Monitors",
    summary: "Bounded-Buffer Producer-Consumer, Readers-Writers concurrency, Dining Philosophers deadlocks, and monitor constructs.",
    difficulty: "Advanced",
    timeComplexity: "O(1)",
    spaceComplexity: "O(N)",
    subtopics: ["Producer-Consumer Buffer Management", "Readers-Writers Reader Preference vs Writer Starvation", "Dining Philosophers Resource Hierarchy Solution", "Monitors & Condition Variables"],
  }),
  createTopic({
    topicId: "os-u4-deadlocks-bankers",
    chapterId: "os-u4-c1",
    unitId: "os-u4",
    subjectId: "os",
    topicNumber: 3,
    title: "Deadlocks, Coffman Conditions & Banker's Algorithm",
    summary: "Mutual exclusion, hold & wait, no preemption, circular wait, resource-allocation graphs, and Banker's safety state matrix algorithm.",
    difficulty: "Advanced",
    timeComplexity: "Banker's: O(M * N^2)",
    spaceComplexity: "O(M * N)",
    subtopics: ["4 Coffman Conditions for Deadlock", "Resource Allocation Graph (RAG) Cycles", "Banker's Safety Algorithm Matrix Math", "Deadlock Prevention vs Avoidance vs Detection"],
  }),

  // Unit 5 Topics
  createTopic({
    topicId: "os-u5-paging-tlb",
    chapterId: "os-u5-c1",
    unitId: "os-u5",
    subjectId: "os",
    topicNumber: 1,
    title: "Memory Paging, Segmentation & TLB Translation",
    summary: "Virtual to physical address translation, Page Tables, multi-level paging, Translation Lookaside Buffer (TLB), and EMAT formula.",
    difficulty: "Advanced",
    timeComplexity: "O(1) with TLB Hit",
    spaceComplexity: "O(N) Page Table",
    subtopics: ["Page Number & Offset Bitwise Math", "TLB Cache & Effective Memory Access Time (EMAT)", "Multi-Level Hierarchical Paging", "Internal vs External Memory Fragmentation"],
  }),
  createTopic({
    topicId: "os-u5-page-replacement",
    chapterId: "os-u5-c1",
    unitId: "os-u5",
    subjectId: "os",
    topicNumber: 2,
    title: "Virtual Memory, Page Faults & Replacement Algorithms",
    summary: "Demand paging, page fault service routine, Belady's anomaly in FIFO, Least Recently Used (LRU), and thrashing working set model.",
    difficulty: "Advanced",
    timeComplexity: "O(1) with Hardware Support",
    spaceComplexity: "O(Frames)",
    subtopics: ["Page Fault Interrupt Handling", "FIFO & Belady's Anomaly", "Least Recently Used (LRU) Hardware Counter", "Thrashing & Working Set Model"],
  }),

  // Unit 6 Topics
  createTopic({
    topicId: "os-u6-file-systems",
    chapterId: "os-u6-c1",
    unitId: "os-u6",
    subjectId: "os",
    topicNumber: 1,
    title: "File Systems, Inodes & Allocation Methods",
    summary: "File control blocks, Unix inode pointers (direct, single, double, triple indirect), contiguous, linked, and indexed block allocation.",
    difficulty: "Intermediate",
    timeComplexity: "O(1) Direct Inode",
    spaceComplexity: "O(Disk Blocks)",
    subtopics: ["Unix Inode Structure", "Contiguous, Linked & Indexed Block Allocation", "Directory Hash Trees vs Linear Lists", "Crash Consistency & Journaling"],
  }),
  createTopic({
    topicId: "os-u6-disk-scheduling-raid",
    chapterId: "os-u6-c1",
    unitId: "os-u6",
    subjectId: "os",
    topicNumber: 2,
    title: "Disk Scheduling (SSTF, SCAN, LOOK) & RAID Levels",
    summary: "Magnetic disk arm movement optimization (FCFS, SSTF, SCAN, C-SCAN, LOOK) and RAID 0, 1, 5, 6, 10 redundancy and parity.",
    difficulty: "Intermediate",
    timeComplexity: "O(N log N)",
    spaceComplexity: "O(1)",
    subtopics: ["Disk Cylinder Head Seek Time", "SSTF vs SCAN vs C-SCAN Algorithms", "RAID 0 Striping & RAID 1 Mirroring", "RAID 5 Distributed Parity Math"],
  }),
];
