/**
 * LearnX B.Tech CSE Comprehensive Curriculum Catalog
 * All 22 Major Computer Science & Engineering Subjects organized across Semesters 1 to 8
 */

export const CURRICULUM_SUBJECTS = [
  // ── SEMESTER 1 ──
  {
    subjectId: "engg-math",
    name: "Engineering Mathematics",
    code: "BS101",
    description: "Calculus, Linear Algebra, Matrix Eigenvalues, Vector Spaces, Differential Equations, and foundational math for computer science algorithms.",
    icon: "📐",
    badge: "Foundations",
    semester: 1,
    difficulty: "Intermediate",
    estimatedHours: 48,
    color: "from-blue-600 to-indigo-600",
    accentColor: "#2563eb",
    order: 1,
    isActive: true,
  },
  {
    subjectId: "cpp",
    name: "C/C++ Programming",
    code: "CS102",
    description: "Low-level memory management, pointers, dynamic memory allocation, memory layouts, structures, STL containers, and systems programming.",
    icon: "💻",
    badge: "Core Systems",
    semester: 1,
    difficulty: "Beginner",
    estimatedHours: 50,
    color: "from-cyan-600 to-blue-700",
    accentColor: "#0284c7",
    order: 2,
    isActive: true,
  },

  // ── SEMESTER 2 ──
  {
    subjectId: "discrete-math",
    name: "Discrete Mathematics",
    code: "CS201",
    description: "Mathematical induction, propositional and predicate logic, set theory, relations, combinatorics, recurrence relations, and graph theory.",
    icon: "🔢",
    badge: "Theoretical",
    semester: 2,
    difficulty: "Intermediate",
    estimatedHours: 45,
    color: "from-purple-600 to-violet-700",
    accentColor: "#7c3aed",
    order: 3,
    isActive: true,
  },
  {
    subjectId: "python",
    name: "Python Programming",
    code: "CS202",
    description: "Modern Python 3 idioms, data structures, functional paradigms, OOP in Python, generators, decorators, NumPy, and scientific computing.",
    icon: "🐍",
    badge: "Programming",
    semester: 2,
    difficulty: "Beginner",
    estimatedHours: 42,
    color: "from-emerald-600 to-teal-700",
    accentColor: "#059669",
    order: 4,
    isActive: true,
  },

  // ── SEMESTER 3 ──
  {
    subjectId: "dsa",
    name: "Data Structures & Algorithms",
    code: "CS301",
    description: "Algorithm analysis, Big-O notations, stacks, queues, linked lists, binary search trees, AVL trees, graphs, heaps, and hashing mechanics.",
    icon: "⚡",
    badge: "Core CSE",
    semester: 3,
    difficulty: "Intermediate",
    estimatedHours: 65,
    color: "from-blue-600 to-indigo-700",
    accentColor: "#2563eb",
    order: 5,
    isActive: true,
  },
  {
    subjectId: "oops",
    name: "Object Oriented Programming",
    code: "CS302",
    description: "Encapsulation, inheritance, runtime polymorphism, virtual functions, abstract classes, interfaces, SOLID principles, and design patterns.",
    icon: "🧩",
    badge: "Software Arch",
    semester: 3,
    difficulty: "Intermediate",
    estimatedHours: 46,
    color: "from-amber-600 to-orange-700",
    accentColor: "#d97706",
    order: 6,
    isActive: true,
  },
  {
    subjectId: "coa",
    name: "Computer Organization & Architecture",
    code: "CS303",
    description: "Digital logic, ALU design, Booth's multiplication, CPU control unit, instruction pipelining, cache memory mapping, virtual memory, and I/O interrupts.",
    icon: "🖥️",
    badge: "Hardware & Arch",
    semester: 3,
    difficulty: "Advanced",
    estimatedHours: 52,
    color: "from-slate-700 to-slate-900",
    accentColor: "#334155",
    order: 7,
    isActive: true,
  },

  // ── SEMESTER 4 ──
  {
    subjectId: "daa",
    name: "Design & Analysis of Algorithms",
    code: "CS401",
    description: "Asymptotic recurrences, Divide & Conquer, Greedy method, Dynamic Programming, Backtracking, Branch & Bound, String Matching, and NP-Completeness.",
    icon: "🎯",
    badge: "Algorithms",
    semester: 4,
    difficulty: "Advanced",
    estimatedHours: 60,
    color: "from-rose-600 to-red-700",
    accentColor: "#e11d48",
    order: 8,
    isActive: true,
  },
  {
    subjectId: "dbms",
    name: "Database Management Systems",
    code: "CS402",
    description: "Relational model, relational algebra, SQL optimization, normalization (1NF-BCNF), ACID properties, concurrency control, B+ tree indexing, and recovery.",
    icon: "🗄️",
    badge: "Core CSE",
    semester: 4,
    difficulty: "Intermediate",
    estimatedHours: 50,
    color: "from-emerald-600 to-teal-700",
    accentColor: "#059669",
    order: 9,
    isActive: true,
  },
  {
    subjectId: "os",
    name: "Operating Systems",
    code: "CS403",
    description: "Process lifecycle, CPU scheduling, thread synchronization, mutexes/semaphores, deadlock detection & prevention, paging, page replacement, and file systems.",
    icon: "⚙️",
    badge: "Core CSE",
    semester: 4,
    difficulty: "Intermediate",
    estimatedHours: 55,
    color: "from-violet-600 to-purple-700",
    accentColor: "#7c3aed",
    order: 10,
    isActive: true,
  },

  // ── SEMESTER 5 ──
  {
    subjectId: "cn",
    name: "Computer Networks",
    code: "CS501",
    description: "OSI & TCP/IP reference architectures, framing, sliding window flow control, CIDR subnetting, Dijkstra/Distance Vector routing, TCP 3-way handshake, and DNS/HTTP.",
    icon: "🌐",
    badge: "Core CSE",
    semester: 5,
    difficulty: "Intermediate",
    estimatedHours: 54,
    color: "from-sky-600 to-blue-700",
    accentColor: "#0284c7",
    order: 11,
    isActive: true,
  },
  {
    subjectId: "toc",
    name: "Theory of Computation",
    code: "CS502",
    description: "Deterministic & Nondeterministic Finite Automata (DFA/NFA), regular expressions, pumping lemma, CFG, Pushdown Automata, Turing machines, and undecidability.",
    icon: "🔄",
    badge: "Theoretical",
    semester: 5,
    difficulty: "Advanced",
    estimatedHours: 50,
    color: "from-indigo-700 to-slate-800",
    accentColor: "#4338ca",
    order: 12,
    isActive: true,
  },
  {
    subjectId: "se",
    name: "Software Engineering",
    code: "CS503",
    description: "SDLC methodologies, Agile, Scrum, requirements engineering, architectural modularity, design patterns, testing strategies, CI/CD, and quality metrics.",
    icon: "📋",
    badge: "Industry Practices",
    semester: 5,
    difficulty: "Intermediate",
    estimatedHours: 42,
    color: "from-teal-600 to-emerald-700",
    accentColor: "#0d9488",
    order: 13,
    isActive: true,
  },
  {
    subjectId: "web-tech",
    name: "Web Technology",
    code: "CS504",
    description: "Modern full-stack web engineering: HTML5/CSS3, ES6+ JavaScript, React components, Node.js, Express REST APIs, MongoDB, JWT auth, and deployment.",
    icon: "⚛️",
    badge: "Applied Tech",
    semester: 5,
    difficulty: "Intermediate",
    estimatedHours: 58,
    color: "from-cyan-600 to-sky-700",
    accentColor: "#0891b2",
    order: 14,
    isActive: true,
  },

  // ── SEMESTER 6 ──
  {
    subjectId: "compiler-design",
    name: "Compiler Design",
    code: "CS601",
    description: "Phases of a compiler, lexical analysis (Lex), parsing techniques (LL, LR, LALR, Yacc), syntax-directed translation, intermediate code generation, and DAG optimization.",
    icon: "🛠️",
    badge: "Systems & Languages",
    semester: 6,
    difficulty: "Advanced",
    estimatedHours: 52,
    color: "from-amber-700 to-yellow-800",
    accentColor: "#b45309",
    order: 15,
    isActive: true,
  },
  {
    subjectId: "ai",
    name: "Artificial Intelligence",
    code: "CS602",
    description: "Intelligent agents, uninformed and heuristic search (A*, IDA*), adversarial game tree search, constraint satisfaction, propositional logic, and probabilistic reasoning.",
    icon: "🤖",
    badge: "AI & Data",
    semester: 6,
    difficulty: "Intermediate",
    estimatedHours: 48,
    color: "from-violet-700 to-indigo-800",
    accentColor: "#6d28d9",
    order: 16,
    isActive: true,
  },
  {
    subjectId: "computer-graphics",
    name: "Computer Graphics",
    code: "CS603",
    description: "Scan conversion (Bresenham's algorithms), 2D/3D affine transformations, Cohen-Sutherland line clipping, parallel/perspective projections, and illumination models.",
    icon: "🎨",
    badge: "Visual Computing",
    semester: 6,
    difficulty: "Intermediate",
    estimatedHours: 44,
    color: "from-fuchsia-600 to-pink-700",
    accentColor: "#c026d3",
    order: 17,
    isActive: true,
  },
  {
    subjectId: "sql",
    name: "SQL",
    code: "CS604",
    description: "Advanced relational query design, window functions (ROW_NUMBER, RANK, LEAD, LAG), CTEs, stored procedures, query execution plans, indexing strategies, and database tuning.",
    icon: "📊",
    badge: "Database Pro",
    semester: 6,
    difficulty: "Intermediate",
    estimatedHours: 40,
    color: "from-emerald-700 to-green-800",
    accentColor: "#047857",
    order: 18,
    isActive: true,
  },

  // ── SEMESTER 7 ──
  {
    subjectId: "ml",
    name: "Machine Learning",
    code: "CS701",
    description: "Supervised and unsupervised learning, linear/logistic regression, SVM, decision trees, random forests, clustering, PCA, backpropagation neural networks, and MLOps.",
    icon: "🧠",
    badge: "AI & Data",
    semester: 7,
    difficulty: "Advanced",
    estimatedHours: 62,
    color: "from-purple-600 to-pink-700",
    accentColor: "#9333ea",
    order: 19,
    isActive: true,
  },
  {
    subjectId: "cloud",
    name: "Cloud Computing",
    code: "CS702",
    description: "Cloud service models (IaaS, PaaS, SaaS), hardware virtualization, containerization with Docker, Kubernetes cluster orchestration, AWS serverless, and cloud storage.",
    icon: "☁️",
    badge: "Cloud & DevOps",
    semester: 7,
    difficulty: "Intermediate",
    estimatedHours: 48,
    color: "from-sky-600 to-indigo-700",
    accentColor: "#0284c7",
    order: 20,
    isActive: true,
  },
  {
    subjectId: "cyber-sec",
    name: "Cyber Security",
    code: "CS703",
    description: "Symmetric and asymmetric cryptography (AES, RSA, ECC), digital signatures, network firewalls, IDS/IPS, OWASP Top 10 vulnerabilities (SQLi, XSS, CSRF), and zero trust.",
    icon: "🔐",
    badge: "Security & Trust",
    semester: 7,
    difficulty: "Advanced",
    estimatedHours: 50,
    color: "from-rose-700 to-slate-900",
    accentColor: "#be123c",
    order: 21,
    isActive: true,
  },

  // ── SEMESTER 8 ──
  {
    subjectId: "java",
    name: "Java Programming",
    code: "CS801",
    description: "Enterprise Java programming, JVM internal mechanics, Java Collections framework, multi-threading, concurrency utilities, Stream API, JDBC, and Spring Boot foundations.",
    icon: "☕",
    badge: "Enterprise Tech",
    semester: 8,
    difficulty: "Intermediate",
    estimatedHours: 55,
    color: "from-orange-600 to-red-700",
    accentColor: "#ea580c",
    order: 22,
    isActive: true,
  },
];
