import { createTopic } from "./builder.js";

export const SYSTEM_DESIGN_UNITS = [
  {
    unitId: "sys-u1",
    subjectId: "system-design",
    unitNumber: 1,
    title: "Unit 1 — System Design Fundamentals",
    description: "Core distributed systems metrics: vertical vs horizontal scalability, high availability, reliability SLAs, latency vs throughput, and CAP theorem.",
    learningObjectives: [
      "Distinguish vertical scaling (scale up) from horizontal scaling (scale out)",
      "Calculate 99.9% vs 99.99% availability and SLA error budgets",
      "Analyze latency p95/p99 percentiles vs overall system throughput (QPS)",
      "Apply the CAP Theorem (Consistency, Availability, Partition Tolerance) to architectural choices",
    ],
    difficulty: "Intermediate",
    estimatedHours: 4.0,
    prerequisites: ["Computer Networks", "Database Fundamentals"],
    practiceQuestionsCount: 15,
    quizQuestionsCount: 10,
    order: 1,
  },
  {
    unitId: "sys-u2",
    subjectId: "system-design",
    unitNumber: 2,
    title: "Unit 2 — Architecture & API Layer",
    description: "Monolithic vs microservices architectures, Client-Server paradigm, REST APIs, API Gateways, Load Balancers, and Service Discovery.",
    learningObjectives: [
      "Compare monolithic simplicity with microservice independent deployability",
      "Evaluate Round Robin, Weighted, Least Connections, and Consistent Hashing load balancing",
      "Implement API Gateway responsibilities (rate limiting, authentication, SSL termination)",
      "Understand Service Discovery registries (Consul, Eureka, Zookeeper)",
    ],
    difficulty: "Advanced",
    estimatedHours: 5.0,
    prerequisites: ["Unit 1 — System Design Fundamentals"],
    practiceQuestionsCount: 18,
    quizQuestionsCount: 12,
    order: 2,
  },
  {
    unitId: "sys-u3",
    subjectId: "system-design",
    unitNumber: 3,
    title: "Unit 3 — Databases, Caching & Storage",
    description: "SQL vs NoSQL selection, primary-replica replication, horizontal sharding, Redis caching strategies, CDNs, and Blob/Object storage.",
    learningObjectives: [
      "Select appropriate database engines (Relational, Key-Value, Document, Wide-Column, Graph)",
      "Implement Cache-Aside, Write-Through, Write-Behind, and Eviction policies (LRU, LFU)",
      "Design database sharding schemes using range, hash, and directory-based routing",
      "Optimize static asset distribution using Edge Content Delivery Networks (CDNs)",
    ],
    difficulty: "Advanced",
    estimatedHours: 5.5,
    prerequisites: ["Database Systems & SQL"],
    practiceQuestionsCount: 20,
    quizQuestionsCount: 15,
    order: 3,
  },
  {
    unitId: "sys-u4",
    subjectId: "system-design",
    unitNumber: 4,
    title: "Unit 4 — Distributed Systems & Asynchronous Messaging",
    description: "Consistency models (strong, eventual), fault tolerance, distributed consensus, Message Queues (Kafka, RabbitMQ), and event-driven architectures.",
    learningObjectives: [
      "Contrast Strong Consistency with Eventual Consistency in multi-datacenter clusters",
      "Implement asynchronous message processing with Apache Kafka and RabbitMQ",
      "Handle at-least-once, at-most-once, and effectively-once delivery semantics",
      "Design idempotent endpoints and dead-letter queues (DLQ)",
    ],
    difficulty: "Advanced",
    estimatedHours: 6.0,
    prerequisites: ["Unit 3 — Databases & Caching"],
    practiceQuestionsCount: 22,
    quizQuestionsCount: 15,
    order: 4,
  },
  {
    unitId: "sys-u5",
    subjectId: "system-design",
    unitNumber: 5,
    title: "Unit 5 — Real-World System Design Case Studies",
    description: "End-to-end FAANG system design architectures: URL Shortener (TinyURL), Real-Time Chat (WhatsApp), Food Delivery (DoorDash), E-Commerce, and Video Streaming (Netflix).",
    learningObjectives: [
      "Estimate QPS, storage requirements, and bandwidth for large-scale systems",
      "Design high-throughput URL Shortener with Base62 encoding and Redis caching",
      "Architect WebSocket connection managers and message stores for real-time chat",
      "Build geo-distributed live driver dispatch and order matching systems",
    ],
    difficulty: "Advanced",
    estimatedHours: 7.0,
    prerequisites: ["Unit 1–4 of System Design"],
    practiceQuestionsCount: 25,
    quizQuestionsCount: 15,
    order: 5,
  },
];

export const SYSTEM_DESIGN_CHAPTERS = SYSTEM_DESIGN_UNITS.map((u) => ({
  chapterId: `${u.unitId}-c1`,
  unitId: u.unitId,
  subjectId: "system-design",
  chapterNumber: 1,
  title: u.title.replace(/Unit \d+ — /, ""),
  description: u.description,
  order: u.unitNumber,
}));

export const SYSTEM_DESIGN_TOPICS = [
  // Unit 1 Topics
  createTopic({
    topicId: "sys-u1-scalability-availability",
    chapterId: "sys-u1-c1",
    unitId: "sys-u1",
    subjectId: "system-design",
    topicNumber: 1,
    title: "Scalability, Availability & Performance Metrics",
    summary: "Vertical vs horizontal scaling, high availability nines calculation (99.99%), latency vs throughput, and SLA/SLO/SLI contracts.",
    difficulty: "Intermediate",
    timeComplexity: "O(1)",
    spaceComplexity: "O(1)",
    subtopics: ["Vertical (Scale-Up) vs Horizontal (Scale-Out)", "SLA, SLO & SLI Definitions", "Latency Percentiles (p50, p95, p99, p99.9)", "Throughput & QPS Calculation Formula"],
  }),
  createTopic({
    topicId: "sys-u1-cap-theorem",
    chapterId: "sys-u1-c1",
    unitId: "sys-u1",
    subjectId: "system-design",
    topicNumber: 2,
    title: "The CAP Theorem & PACELC Theorem",
    summary: "Trade-offs in distributed data stores: Consistency, Availability, Partition Tolerance, and PACELC latency vs consistency trade-offs.",
    difficulty: "Intermediate",
    timeComplexity: "O(1)",
    spaceComplexity: "O(1)",
    subtopics: ["Why Network Partitions Are Inevitable", "CP Systems (HBase, Spanner) vs AP Systems (Cassandra, Dynamo)", "PACELC Extension (Else Latency vs Consistency)", "Eventual Consistency & Read Repair"],
  }),

  // Unit 2 Topics
  createTopic({
    topicId: "sys-u2-microservices-api-gateway",
    chapterId: "sys-u2-c1",
    unitId: "sys-u2",
    subjectId: "system-design",
    topicNumber: 1,
    title: "Microservices Architecture & API Gateway",
    summary: "Decomposing monoliths into microservices, bounded contexts, API Gateway edge security, request routing, rate limiting, and circuit breakers.",
    difficulty: "Advanced",
    timeComplexity: "O(1)",
    spaceComplexity: "O(Service Count)",
    subtopics: ["Monolith vs Microservices Trade-Offs", "API Gateway Responsibilities (Auth, SSL, Routing)", "Circuit Breaker Pattern (Netflix Hystrix / Resilience4j)", "Service Discovery (Client-Side vs Server-Side)"],
  }),
  createTopic({
    topicId: "sys-u2-load-balancers",
    chapterId: "sys-u2-c1",
    unitId: "sys-u2",
    subjectId: "system-design",
    topicNumber: 2,
    title: "Load Balancers & Consistent Hashing",
    summary: "Layer 4 vs Layer 7 load balancing, algorithms (Round Robin, Least Connections), and Consistent Hashing with virtual nodes for distributed caches.",
    difficulty: "Advanced",
    timeComplexity: "O(log K) Consistent Hash Ring",
    spaceComplexity: "O(K) Nodes",
    subtopics: ["Layer 4 (Transport) vs Layer 7 (Application) Routing", "Round Robin, Weighted, Least Connections", "Consistent Hashing Ring Concept", "Virtual Nodes to Prevent Hash Ring Skew"],
  }),

  // Unit 3 Topics
  createTopic({
    topicId: "sys-u3-caching-redis-cdn",
    chapterId: "sys-u3-c1",
    unitId: "sys-u3",
    subjectId: "system-design",
    topicNumber: 1,
    title: "Caching Strategies (Redis) & CDNs",
    summary: "In-memory caching patterns (Cache-Aside, Write-Through, Write-Behind), TTL expiration, eviction policies (LRU, LFU), and Edge CDNs.",
    difficulty: "Advanced",
    timeComplexity: "O(1) Redis In-Memory Lookup",
    spaceComplexity: "O(Cache Memory)",
    subtopics: ["Cache-Aside (Lazy Loading) vs Write-Through", "Cache Invalidation Challenges & Thundering Herd", "LRU (Least Recently Used) Eviction Algorithm", "CDN Edge Caching for Static Assets"],
  }),
  createTopic({
    topicId: "sys-u3-sharding-replication",
    chapterId: "sys-u3-c1",
    unitId: "sys-u3",
    subjectId: "system-design",
    topicNumber: 2,
    title: "Database Scaling: Replication & Horizontal Sharding",
    summary: "Primary-Replica read scaling, split-brain problem, horizontal sharding keys, range vs hash partitioning, and distributed transactions.",
    difficulty: "Advanced",
    timeComplexity: "O(1) Shard Key Routing",
    spaceComplexity: "O(Cluster Storage)",
    subtopics: ["Master-Slave (Primary-Replica) Asynchronous Replication", "Sharding Key Selection & Hotspot Elimination", "Hash-Based vs Range-Based Partitioning", "Distributed Joins & Cross-Shard Queries"],
  }),

  // Unit 4 Topics
  createTopic({
    topicId: "sys-u4-message-queues-kafka",
    chapterId: "sys-u4-c1",
    unitId: "sys-u4",
    subjectId: "system-design",
    topicNumber: 1,
    title: "Message Queues & Event-Driven Architecture (Kafka)",
    summary: "Point-to-point queues vs pub-sub topic logs, Kafka partitions, consumer groups, backpressure handling, and idempotent message consumption.",
    difficulty: "Advanced",
    timeComplexity: "O(1) Append to Commit Log",
    spaceComplexity: "O(Message Retention)",
    subtopics: ["Message Queues vs Event Streams (RabbitMQ vs Kafka)", "Kafka Partitioning & Consumer Group Offsets", "At-Least-Once Delivery & Idempotent Keys", "Dead-Letter Queues (DLQ) for Failed Poison Messages"],
  }),

  // Unit 5 Topics
  createTopic({
    topicId: "sys-u5-url-shortener",
    chapterId: "sys-u5-c1",
    unitId: "sys-u5",
    subjectId: "system-design",
    topicNumber: 1,
    title: "System Design: Scalable URL Shortener (TinyURL)",
    summary: "Capacity estimations, Base62 token generation, collision resolution, distributed unique ID generation (Snowflake), and read-heavy Redis caching.",
    difficulty: "Advanced",
    timeComplexity: "O(1) Redirect",
    spaceComplexity: "O(Total Links)",
    subtopics: ["Traffic & Storage Capacity Estimation Math", "Base62 Encoding vs MD5 Hash Truncation", "Twitter Snowflake Distributed ID Generator", "High-Throughput 301 vs 302 Redirection"],
  }),
  createTopic({
    topicId: "sys-u5-chat-app",
    chapterId: "sys-u5-c1",
    unitId: "sys-u5",
    subjectId: "system-design",
    topicNumber: 2,
    title: "System Design: Real-Time Chat System (WhatsApp / Slack)",
    summary: "Persistent bi-directional WebSocket connections, chat servers cluster, message presence servers, Cassandra/HBase message history, and push notifications.",
    difficulty: "Advanced",
    timeComplexity: "O(1) Real-Time Push",
    spaceComplexity: "O(Active Connections)",
    subtopics: ["HTTP Long-Polling vs WebSockets", "WebSocket Connection Manager Cluster", "Message Sequencing & Delivery Receipts (Sent, Delivered, Read)", "Presence Server Heartbeats & Redis Pub/Sub"],
  }),
  createTopic({
    topicId: "sys-u5-streaming-ecommerce",
    chapterId: "sys-u5-c1",
    unitId: "sys-u5",
    subjectId: "system-design",
    topicNumber: 3,
    title: "System Design: Video Streaming (Netflix) & E-Commerce",
    summary: "Video chunking, Adaptive Bitrate Streaming (HLS/DASH), multi-CDN routing, distributed inventory reservations, and payment saga patterns.",
    difficulty: "Advanced",
    timeComplexity: "O(1) Streaming Chunk Download",
    spaceComplexity: "O(Petabytes Storage)",
    subtopics: ["Video Encoding Pipeline & Transcoding", "HLS (HTTP Live Streaming) Adaptive Chunking", "Distributed Inventory Locking (Pessimistic vs Optimistic)", "Saga Pattern for Distributed Payment Orchestration"],
  }),
];
