import { createTopic } from "./builder.js";

export const WEB_DEV_UNITS = [
  {
    unitId: "web-u1",
    subjectId: "web-dev",
    unitNumber: 1,
    title: "Unit 1 — Modern HTML5 & CSS3 Architecture",
    description: "Semantic HTML5, accessible forms, tables, CSS box model, Flexbox 1D alignment, CSS Grid 2D layouts, and mobile-first responsive design.",
    learningObjectives: [
      "Structure accessible documents using semantic HTML5 tags (<header>, <main>, <article>, <nav>)",
      "Build validated web forms with HTML5 input constraints and accessibility ARIA attributes",
      "Master CSS Box Model (margin, border, padding, content-box vs border-box)",
      "Construct responsive multi-column layouts with CSS Flexbox, Grid, and Media Queries",
    ],
    difficulty: "Beginner",
    estimatedHours: 3.5,
    prerequisites: ["None"],
    practiceQuestionsCount: 15,
    quizQuestionsCount: 10,
    order: 1,
  },
  {
    unitId: "web-u2",
    subjectId: "web-dev",
    unitNumber: 2,
    title: "Unit 2 — Modern JavaScript (ES6+) & Asynchronous Engine",
    description: "JS types, execution context, call stack, closures, prototypes, event delegation, ES6+ features, Promises, Event Loop, and Async/Await.",
    learningObjectives: [
      "Trace JavaScript Execution Context, Hoisting, and Lexical Closures",
      "Manipulate the DOM tree efficiently and handle events with Event Bubbling/Capturing",
      "Master ES6+ arrow functions, destructuring, spread/rest operators, and modules",
      "Understand the JavaScript Event Loop, Microtask Queue (Promises), and Macrotask Queue (setTimeout)",
    ],
    difficulty: "Intermediate",
    estimatedHours: 4.5,
    prerequisites: ["Unit 1 — HTML & CSS"],
    practiceQuestionsCount: 20,
    quizQuestionsCount: 12,
    order: 2,
  },
  {
    unitId: "web-u3",
    subjectId: "web-dev",
    unitNumber: 3,
    title: "Unit 3 — React & Component Engineering",
    description: "React Virtual DOM reconciliation, components, props, state immutability, React Hooks (useState, useEffect, useMemo, useCallback), and React Router.",
    learningObjectives: [
      "Understand Virtual DOM diffing (Fiber architecture) vs Direct DOM manipulation",
      "Manage component state, unidirectional data flow, and controlled form inputs",
      "Master Hooks lifecycle synchronization with useEffect, useMemo, and useCallback",
      "Implement client-side routing with React Router v6 and Axios HTTP integrations",
    ],
    difficulty: "Intermediate",
    estimatedHours: 5.5,
    prerequisites: ["Unit 2 — Modern JavaScript"],
    practiceQuestionsCount: 22,
    quizQuestionsCount: 15,
    order: 3,
  },
  {
    unitId: "web-u4",
    subjectId: "web-dev",
    unitNumber: 4,
    title: "Unit 4 — Backend Engineering: Node.js, Express & MongoDB",
    description: "Node.js asynchronous event-driven I/O, Express routing and middleware pipeline, RESTful API design, JWT stateless authentication, and Mongoose ODM.",
    learningObjectives: [
      "Build high-throughput REST APIs using Express.js routers and middleware chains",
      "Implement secure authentication with bcrypt password hashing and JSON Web Tokens (JWT)",
      "Design normalized and embedded document schemas in MongoDB using Mongoose",
      "Handle API error propagation, CORS policies, and rate-limiting middleware",
    ],
    difficulty: "Advanced",
    estimatedHours: 5.5,
    prerequisites: ["Unit 2 — Modern JavaScript"],
    practiceQuestionsCount: 20,
    quizQuestionsCount: 15,
    order: 4,
  },
  {
    unitId: "web-u5",
    subjectId: "web-dev",
    unitNumber: 5,
    title: "Unit 5 — DevOps, Docker & Cloud Deployment",
    description: "Git branching strategies, Linux server administration, Docker containerization, multi-stage builds, CI/CD pipelines (GitHub Actions), and AWS/Vercel cloud deployment.",
    learningObjectives: [
      "Master Git workflows (feature branching, rebasing, merge conflict resolution)",
      "Write multi-stage Dockerfiles for optimized lightweight production images",
      "Configure automated GitHub Actions workflows for linting, testing, and deployment",
      "Deploy scalable frontend (Vercel/Cloudflare) and containerized backend microservices (AWS EC2, Render)",
    ],
    difficulty: "Advanced",
    estimatedHours: 5.0,
    prerequisites: ["Unit 4 — Backend Engineering"],
    practiceQuestionsCount: 18,
    quizQuestionsCount: 12,
    order: 5,
  },
];

export const WEB_DEV_CHAPTERS = WEB_DEV_UNITS.map((u) => ({
  chapterId: `${u.unitId}-c1`,
  unitId: u.unitId,
  subjectId: "web-dev",
  chapterNumber: 1,
  title: u.title.replace(/Unit \d+ — /, ""),
  description: u.description,
  order: u.unitNumber,
}));

export const WEB_DEV_TOPICS = [
  // Unit 1 Topics
  createTopic({
    topicId: "web-u1-semantic-html-forms",
    chapterId: "web-u1-c1",
    unitId: "web-u1",
    subjectId: "web-dev",
    topicNumber: 1,
    title: "Semantic HTML5, Forms & Accessibility (a11y)",
    summary: "Document structure with semantic landmarks, accessible form validations, input constraints, and ARIA screen reader attributes.",
    difficulty: "Beginner",
    timeComplexity: "O(1)",
    spaceComplexity: "O(DOM Tree)",
    subtopics: ["Semantic HTML5 Tags vs Generic <div>", "Accessible Form Controls & Input Types", "Table Elements & Headers for Tabular Data", "ARIA Roles & Keyboard Accessibility"],
  }),
  createTopic({
    topicId: "web-u1-css-flexbox-grid",
    chapterId: "web-u1-c1",
    unitId: "web-u1",
    subjectId: "web-dev",
    topicNumber: 2,
    title: "CSS Box Model, Flexbox & 2D Grid Layouts",
    summary: "Box-sizing border-box, Flexbox axis alignment (justify-content, align-items), CSS Grid template columns, and mobile-first media queries.",
    difficulty: "Beginner",
    timeComplexity: "O(1) CSS Render",
    spaceComplexity: "O(1)",
    subtopics: ["CSS Box Model (Margin, Border, Padding, Content)", "Flexbox 1D Layouts & Main/Cross Axes", "CSS Grid 2D Templates & Areas", "Responsive Design & Mobile-First Breakpoints"],
  }),

  // Unit 2 Topics
  createTopic({
    topicId: "web-u2-js-engine-closures",
    chapterId: "web-u2-c1",
    unitId: "web-u2",
    subjectId: "web-dev",
    topicNumber: 1,
    title: "JavaScript Engine: Scope, Closures & DOM Events",
    summary: "V8 Call Stack, execution context phases, closures in functional programming, DOM tree traversal, and Event Bubbling/Capturing delegation.",
    difficulty: "Intermediate",
    timeComplexity: "O(1)",
    spaceComplexity: "O(Closure Scope)",
    subtopics: ["Call Stack & Memory Heap in V8", "Lexical Scope & Closures Mechanics", "DOM Manipulation & Query Selectors", "Event Bubbling, Capturing & Delegation"],
  }),
  createTopic({
    topicId: "web-u2-async-eventloop",
    chapterId: "web-u2-c1",
    unitId: "web-u2",
    subjectId: "web-dev",
    topicNumber: 2,
    title: "Asynchronous JavaScript: Event Loop, Promises & Async/Await",
    summary: "Event loop microtask (Promises) vs macrotask (timers) priorities, Promise chaining, error handling, Async/Await syntax, and Fetch API.",
    difficulty: "Intermediate",
    timeComplexity: "O(1) Event Loop Dispatch",
    spaceComplexity: "O(Queue Size)",
    subtopics: ["Event Loop, Call Stack & Callback Queue", "Microtask Queue (Promise.then) vs Macrotask Queue", "Creating & Consuming Promises", "Async/Await with Try/Catch and Fetch API"],
  }),

  // Unit 3 Topics
  createTopic({
    topicId: "web-u3-react-basics-vdom",
    chapterId: "web-u3-c1",
    unitId: "web-u3",
    subjectId: "web-dev",
    topicNumber: 1,
    title: "React Fundamentals: JSX, Virtual DOM & Props/State",
    summary: "JSX compilation, Virtual DOM reconciliation (React Fiber), functional components, unidirectional data flow, and immutable state updates.",
    difficulty: "Intermediate",
    timeComplexity: "O(N) Tree Diffing",
    spaceComplexity: "O(Component Tree)",
    subtopics: ["Declarative JSX Compilation to React.createElement", "Virtual DOM Diffing & Reconciliation Keys", "Props vs State in Functional Components", "Lifting State Up Pattern"],
  }),
  createTopic({
    topicId: "web-u3-react-hooks-router",
    chapterId: "web-u3-c1",
    unitId: "web-u3",
    subjectId: "web-dev",
    topicNumber: 2,
    title: "React Hooks (useState, useEffect) & React Router",
    summary: "useState for state management, useEffect dependency array synchronization, useMemo/useCallback performance memoization, and React Router v6.",
    difficulty: "Intermediate",
    timeComplexity: "O(1) Hook Access",
    spaceComplexity: "O(Hook State)",
    subtopics: ["useState & Functional State Updates", "useEffect Lifecycle & Cleanup Functions", "useMemo & useCallback Performance Optimization", "Client-Side SPA Routing with React Router"],
  }),

  // Unit 4 Topics
  createTopic({
    topicId: "web-u4-nodejs-express-rest",
    chapterId: "web-u4-c1",
    unitId: "web-u4",
    subjectId: "web-dev",
    topicNumber: 1,
    title: "Node.js Architecture & Express RESTful APIs",
    summary: "Node.js non-blocking libuv event loop, Express middleware pipeline (req, res, next), HTTP status codes, and REST architectural constraints.",
    difficulty: "Advanced",
    timeComplexity: "O(1) Route Matching",
    spaceComplexity: "O(Request Context)",
    subtopics: ["Single-Threaded Event Loop & libuv Thread Pool", "Express Middleware Pipeline & Error Handlers", "RESTful URL Design & Standard HTTP Status Codes", "Request Body Parsing & Validation"],
  }),
  createTopic({
    topicId: "web-u4-auth-jwt-mongodb",
    chapterId: "web-u4-c1",
    unitId: "web-u4",
    subjectId: "web-dev",
    topicNumber: 2,
    title: "Authentication (JWT & Bcrypt) & MongoDB with Mongoose",
    summary: "Salting and hashing passwords with bcrypt, JSON Web Token (JWT) stateless auth headers, and Mongoose ODM schema validation and queries.",
    difficulty: "Advanced",
    timeComplexity: "O(1) Token Verify, O(log N) Indexed Query",
    spaceComplexity: "O(N) DB Storage",
    subtopics: ["Password Salting & Bcrypt Hashing", "JWT Header, Payload & Signature Verification", "Protected Route Middleware in Express", "Mongoose Schemas, Indexes & Relationships"],
  }),

  // Unit 5 Topics
  createTopic({
    topicId: "web-u5-git-linux",
    chapterId: "web-u5-c1",
    unitId: "web-u5",
    subjectId: "web-dev",
    topicNumber: 1,
    title: "Git Version Control & Linux Server Basics",
    summary: "Git commit directed acyclic graphs (DAG), branching, rebasing, merge conflicts, Linux file permissions (chmod, chown), and process management (systemd, top).",
    difficulty: "Intermediate",
    timeComplexity: "O(1) Commit Append",
    spaceComplexity: "O(Repo History)",
    subtopics: ["Git Staging, Commits & Branch Pointers", "Git Merge vs Rebase Workflow", "Linux Permissions & Bash CLI Scripting", "Process Management (systemctl, ps, kill)"],
  }),
  createTopic({
    topicId: "web-u5-docker-cicd-cloud",
    chapterId: "web-u5-c1",
    unitId: "web-u5",
    subjectId: "web-dev",
    topicNumber: 2,
    title: "Docker Containerization, CI/CD & Cloud Deployment",
    summary: "Docker images, containers, multi-stage Dockerfiles, Docker Compose, automated GitHub Actions pipelines, and cloud hosting (Vercel, AWS EC2, Render).",
    difficulty: "Advanced",
    timeComplexity: "O(1) Container Execution",
    spaceComplexity: "O(Image Size)",
    subtopics: ["Containers vs Virtual Machines (cgroups, namespaces)", "Multi-Stage Dockerfile Optimization", "GitHub Actions CI/CD YAML Pipelines", "Cloud Deployment Architecture (AWS, Vercel, Render)"],
  }),
];
